import type { MediaItem } from './news';

export type VideoItem = MediaItem & {
  thumbnail?: string;
  icon: string;
};

// Long-form recordings and selected clips. Duplicate mirrors and social
// reposts are deliberately omitted in favour of the most complete source.
export const videoItems: VideoItem[] = [
  { title: 'هوش مصنوعی ایران برای اولین بار طلایی شد', source: 'همشهری', kind: 'ویدئو', summary: 'گفت‌وگو درباره نخستین مدال طلای ایران در المپیاد جهانی هوش مصنوعی و دستاورد تیم ملی در سومین دوره رقابت‌ها.', url: 'https://www.hamshahrionline.ir/news/1059157/', date: '2026-08-08', faDate: '۱۷ مرداد ۱۴۰۵', icon: 'fa-solid fa-play' },
  { title: 'ورق ترجمه؛ از دوره ذبیح‌الله منصوری تا هوش مصنوعی', source: 'رادیو تهران', kind: 'صوت', summary: 'بحث برنامه «چراغ» درباره مسیر ترجمه، تغییر نقش مترجم و اثر هوش مصنوعی بر آینده زبان و صنعت ترجمه.', url: 'http://radiotehran.ir/videodetails/?m=100009&n=1568869', date: '2025-11-22', faDate: '۱ آذر ۱۴۰۴', icon: 'fa-solid fa-headphones' },
  { title: 'صداوسیما به سمت هوشمندسازی رسانه با داده‌های ملی حرکت می‌کند', source: 'رادیو تهران', kind: 'صوت', summary: 'گفت‌وگوی برنامه «چراغ» درباره داده‌های رسانه ملی، اجرانشدن کامل قانون مدیریت داده‌ها و ضرورت زیرساخت پردازشی و مهندسی کاربردی.', url: 'http://radiotehran.ir/videodetails/?m=100009&n=1555741', date: '2025-10-16', faDate: '۲۴ مهر ۱۴۰۴', icon: 'fa-solid fa-headphones' },
  { title: 'گفت‌وگو درباره مانع داده و کاربردی‌سازی هوش مصنوعی', source: 'آینو', kind: 'ویدئوی کوتاه', summary: 'گفت‌وگویی کوتاه درباره کمبود داده‌های متمرکز، نقش فرهنگ‌سازی کمیسیون و مسیر اتصال هوش مصنوعی به مسئله‌های صنعت و کشاورزی.', url: 'https://www.instagram.com/reel/DPqqXOVDbD1/', date: '2025-10-11', faDate: '۱۹ مهر ۱۴۰۴', icon: 'fa-brands fa-instagram' },
  { title: 'زیرساخت هوش مصنوعی در ایران؛ از سند ملی تا واقعیت کمبودها', source: 'پادکست دی‌باگر', kind: 'ویدئو پادکست', summary: 'گفت‌وگویی یک‌ساعته درباره فاصله سند ملی با واقعیت، کمبود برق و اینترنت، زیرساخت GPU، سکوی ملی و راه جبران عقب‌ماندگی ایران.', url: 'https://www.youtube.com/watch?v=wOwhJSIr-2E', date: '2025-09-28', faDate: '۶ مهر ۱۴۰۴', thumbnail: 'https://i.ytimg.com/vi/wOwhJSIr-2E/hqdefault.jpg', icon: 'fa-brands fa-youtube' },
  { title: 'تجاری‌سازی هوش مصنوعی و ارائه خدمات به‌صورت سرویس ابری', source: 'الکامپ', kind: 'سخنرانی', summary: 'سخنرانی تخصصی در الکامپ درباره مدل سرویس ابری، مسیر تجاری‌سازی و پیش‌نیازهای تبدیل فناوری هوش مصنوعی به خدمتی قابل ارائه.', url: 'https://www.youtube.com/watch?v=Squ-9odTru4', date: '2025-09-25', faDate: '۳ مهر ۱۴۰۴', thumbnail: 'https://i.ytimg.com/vi/Squ-9odTru4/hqdefault.jpg', icon: 'fa-brands fa-youtube' },
  { title: 'جنگ بی‌صدا؛ نبرد هوش مصنوعی علیه هوش مصنوعی', source: 'رادیو تهران', kind: 'صوت', summary: 'بحث برنامه «چراغ» درباره حمله‌های هوشمند، تقابل مدل‌ها و اینکه هوش مصنوعی چگونه هم‌زمان ابزار حمله و دفاع در محیط‌های متخاصم می‌شود.', url: 'http://radiotehran.ir/videodetails/?m=100009&n=1538073', date: '2025-08-31', faDate: '۹ شهریور ۱۴۰۴', icon: 'fa-solid fa-headphones' },
  { title: 'هوش مصنوعی، تعصب الگوریتم‌ها و تبعیض پنهان', source: 'رادیو تهران', kind: 'صوت', summary: 'گفت‌وگوی برنامه «چراغ» درباره سوگیری الگوریتمی، تبعیض دیجیتال و مسئولیت طراحان و بهره‌برداران در برابر آسیب‌های پنهان سامانه‌های هوشمند.', url: 'http://radiotehran.ir/videodetails/?m=100009&n=1530170', date: '2025-08-03', faDate: '۱۲ مرداد ۱۴۰۴', icon: 'fa-solid fa-headphones' },
  { title: 'ربات‌های انسان‌نما و انقلاب‌های صنعتی', source: 'رادیو تهران', kind: 'صوت', summary: 'گفت‌وگو درباره جایگاه ربات‌های انسان‌نما در زنجیره تحولات صنعتی، تفاوت نمایش فناورانه با کاربرد و آینده تعامل انسان و ماشین.', url: 'http://radiotehran.ir/videodetails/?m=100009&n=1526117', date: '2025-07-21', faDate: '۳۰ تیر ۱۴۰۴', icon: 'fa-solid fa-headphones' },
  { title: 'حکومت داده‌ها دست کیست؟', source: 'برنامه چراغ', kind: 'ویدئوی کوتاه', summary: 'بحثی درباره مالکیت، دسترسی و حکمرانی داده؛ با حضور مهران ضیابری و محمد غلامی در برنامه «چراغ» رادیو تهران.', url: 'https://www.instagram.com/reel/DL9Aa3EItyJ/', date: '2025-07-15', faDate: 'تیر ۱۴۰۴', icon: 'fa-brands fa-instagram' },
  { title: 'آینده هوش مصنوعی', source: 'فیوتاک', kind: 'گفت‌وگوی ویدئویی', summary: 'گفت‌وگوی ۵۲ دقیقه‌ای دکتر مهدی محمدی با مهران ضیابری درباره آینده هوش مصنوعی، تجاری‌سازی، دغدغه‌های ملی و تجربه ساخت ترگمان.', url: 'https://www.youtube.com/watch?v=HO7Cawjkog8', date: '2024-12-24', faDate: '۴ دی ۱۴۰۳', thumbnail: 'https://i.ytimg.com/vi/HO7Cawjkog8/hqdefault.jpg', icon: 'fa-brands fa-youtube' },
  { title: 'هوش مصنوعی چه مشاغلی را از بین می‌برد؟', source: 'کارگاه', kind: 'پادکست', summary: 'گفت‌وگوی ۸۶ دقیقه‌ای درباره آینده کار، مشاغل در معرض تغییر و مرز میان جایگزینی انسان و تغییر شکل مهارت‌ها پس از همه‌گیرشدن ChatGPT.', url: 'https://shows.acast.com/kargah/episodes/639cd492f6e39d00116bb8cd', date: '2022-12-17', faDate: '۲۶ آذر ۱۴۰۱', icon: 'fa-solid fa-podcast' }
];
