import type { MediaItem } from './news';

export type VideoItem = Omit<MediaItem, 'coverImage' | 'coverImageAlt' | 'editorialNote'> & {
  thumbnail?: string;
  icon: string;
};

// Long-form recordings and selected clips. Duplicate mirrors and social
// reposts are deliberately omitted in favour of the most complete source.
export const videoItems: VideoItem[] = [
  { title: "گفت‌وگو با مهران ضیابری در الکامپ ۲۹", source: "هومص", kind: "گفت‌وگوی ویدئویی", summary: "مصاحبه با مهران ضیابری، معاون فنی صندوق سرمایه‌گذاری هومص، در الکامپ ۲۹. این ویدئو در صفحه رسمی هومص در لینکدین منتشر شده است.", url: "https://www.linkedin.com/posts/hoomas_مصاحبه-با-مهران-ضیابری-معاون-فنی-صندوق-سرمایهگذاری-activity-7502684269819916289-uz0r/", date: "2026-09-07", faDate: "۱۶ شهریور ۱۴۰۵", thumbnail: "/images/media-covers/linkedin-7502684269819916289.jpg", icon: "fa-brands fa-linkedin" },
  { title: 'هوش مصنوعی؛ حفظ یا حذف زبان‌های محلی', source: 'رادیو تهران', kind: 'صوت', summary: 'برنامه «چراغ» درباره نسبت هوش مصنوعی با زبان‌های محلی و پرسش حفظ یا حذف آن‌ها، با اجرای هدی فلاح. این برنامه ۸۰ دقیقه‌ای در ۱۴ شهریور ۱۴۰۵ پخش شده و قطعات آن در آرشیو ایران‌صدا قابل شنیدن است.', url: 'http://radio.iranseda.ir/epgarchivePart/?VALID=TRUE&ch=20&e=153952809', date: '2026-09-05', faDate: '۱۴ شهریور ۱۴۰۵', thumbnail: '/images/media-covers/cheragh-104121.jpg', icon: 'fa-solid fa-headphones' },
  { title: "بازدید آینده‌سازان ایران از غرفه بهین تکنولوژی", source: "بهین تکنولوژی", kind: "ویدئوی کوتاه", summary: "گزارش تصویری بهین تکنولوژی از بازدید آینده‌سازان ایران از غرفه این شرکت و گفت‌وگوی مهندس توسلی با بازدیدکنندگان؛ منتشرشده در صفحه رسمی بهین تکنولوژی در اینستاگرام.", url: "https://www.instagram.com/reel/Dcx7lhtM6GJ/", date: "2026-09-02", faDate: "۱۱ شهریور ۱۴۰۵", thumbnail: "/images/media-covers/instagram-Dcx7lhtM6GJ.jpg", icon: "fa-brands fa-instagram" },
  { title: "نشست خبری رونمایی از عیار هومص", source: "هومص", kind: "ویدئو", summary: "ویدئوی منتشرشده در صفحه رسمی هومص از نشست خبری رونمایی دستیار هوشمند عیار با حضور اهالی رسانه. این نشست در اول شهریور ۱۴۰۵ برگزار شده است.", url: "https://www.instagram.com/reel/DcjTg2eowqD/", date: "2026-08-27", faDate: "۵ شهریور ۱۴۰۵", thumbnail: "/images/media-covers/instagram-DcjTg2eowqD.jpg", icon: "fa-brands fa-instagram" },
  { title: "خلاصه دورهمی و نشست خبری رونمایی از دستیار هوشمند عیار", source: "آرش سروری", kind: "ویدئوی کوتاه", summary: "کلیپ خلاصه رویداد رونمایی از دستیار هوشمند عیار صندوق هومص، با حضور محمدرضا معبودیان، مهران ضیابری و دیگر اعضای مجموعه. رویداد در اول شهریور ۱۴۰۵ با راهبری آرش سروری برگزار شده است.", url: "https://www.instagram.com/reel/DcfaZFdoB_D/", date: "2026-08-25", faDate: "۳ شهریور ۱۴۰۵", thumbnail: "/images/media-covers/instagram-DcfaZFdoB_D.jpg", icon: "fa-brands fa-instagram" },
  { title: 'هوش مصنوعی ایران برای اولین بار طلایی شد', source: 'همشهری', kind: 'ویدئو', summary: 'گفت‌وگو درباره نخستین مدال طلای ایران در المپیاد جهانی هوش مصنوعی و دستاورد تیم ملی در سومین دوره رقابت‌ها.', url: 'https://www.hamshahrionline.ir/news/1059157/', date: '2026-08-08', faDate: '۱۷ مرداد ۱۴۰۵', thumbnail: '/images/media-covers/hamshahri-1059157.jpg', icon: 'fa-solid fa-play' },
  { title: 'مدل‌های استدلال‌گر؛ آیا هوش مصنوعی‌ها بهتر فکر می‌کنند؟ — قسمت دوم', source: 'رادیو تهران', kind: 'صوت', summary: 'قسمت دوم گفت‌وگوی برنامه «چراغ» درباره مدل‌های استدلال‌گر و توانایی آن‌ها در فکر کردن، با حضور مهران ضیابری و امیرحسین برشویی و اجرای هدی فلاح. این برنامه ۸۰ دقیقه‌ای در ۲۴ تیر ۱۴۰۵ از رادیو تهران پخش شده است.', url: 'http://radio.iranseda.ir/epgarchivePart/?VALID=TRUE&ch=20&e=153891069', date: '2026-07-15', faDate: '۲۴ تیر ۱۴۰۵', thumbnail: '/images/media-covers/cheragh-104121.jpg', icon: 'fa-solid fa-headphones' },
  { title: 'مدل‌های استدلال‌گر؛ آیا هوش مصنوعی‌ها بهتر فکر می‌کنند؟', source: 'رادیو تهران', kind: 'صوت', summary: 'گفت‌وگوی برنامه «چراغ» درباره مدل‌های استدلال‌گر و این پرسش که آیا هوش مصنوعی‌ها بهتر فکر می‌کنند، با حضور مهران ضیابری و امیرحسین برشویی و اجرای هدی فلاح. این برنامه ۸۰ دقیقه‌ای در ۲۰ تیر ۱۴۰۵ پخش شده و در آرشیو ایران‌صدا در دسترس است.', url: 'http://radio.iranseda.ir/epgarchivePart/?VALID=TRUE&ch=20&e=153891453', date: '2026-07-11', faDate: '۲۰ تیر ۱۴۰۵', thumbnail: '/images/media-covers/cheragh-104121.jpg', icon: 'fa-solid fa-headphones' },
  { title: 'ورق ترجمه؛ از دوره ذبیح‌الله منصوری تا هوش مصنوعی', source: 'رادیو تهران', kind: 'صوت', summary: 'بحث برنامه «چراغ» درباره مسیر ترجمه، تغییر نقش مترجم و اثر هوش مصنوعی بر آینده زبان و صنعت ترجمه.', url: 'http://radiotehran.ir/videodetails/?m=100009&n=1568869', date: '2025-11-22', faDate: '۱ آذر ۱۴۰۴', thumbnail: '/images/media-covers/radiotehran-1568869.jpg', icon: 'fa-solid fa-headphones' },
  { title: 'صداوسیما به سمت هوشمندسازی رسانه با داده‌های ملی حرکت می‌کند', source: 'رادیو تهران', kind: 'صوت', summary: 'گفت‌وگوی برنامه «چراغ» درباره داده‌های رسانه ملی، اجرانشدن کامل قانون مدیریت داده‌ها و ضرورت زیرساخت پردازشی و مهندسی کاربردی.', url: 'http://radiotehran.ir/videodetails/?m=100009&n=1555741', date: '2025-10-16', faDate: '۲۴ مهر ۱۴۰۴', thumbnail: '/images/media-covers/radiotehran-1555741.jpg', icon: 'fa-solid fa-headphones' },
  { title: 'گفت‌وگو درباره مانع داده و کاربردی‌سازی هوش مصنوعی', source: 'آینو', kind: 'ویدئوی کوتاه', summary: 'گفت‌وگویی کوتاه درباره کمبود داده‌های متمرکز، نقش فرهنگ‌سازی کمیسیون و مسیر اتصال هوش مصنوعی به مسئله‌های صنعت و کشاورزی.', url: 'https://www.instagram.com/reel/DPqqXOVDbD1/', date: '2025-10-11', faDate: '۱۹ مهر ۱۴۰۴', thumbnail: '/images/media-covers/instagram-DPqqXOVDbD1.jpg', icon: 'fa-brands fa-instagram' },
  { title: 'زیرساخت هوش مصنوعی در ایران؛ از سند ملی تا واقعیت کمبودها', source: 'پادکست دی‌باگر', kind: 'ویدئو پادکست', summary: 'گفت‌وگویی یک‌ساعته درباره فاصله سند ملی با واقعیت، کمبود برق و اینترنت، زیرساخت GPU، سکوی ملی و راه جبران عقب‌ماندگی ایران.', url: 'https://www.youtube.com/watch?v=wOwhJSIr-2E', date: '2025-09-28', faDate: '۶ مهر ۱۴۰۴', thumbnail: '/images/media-covers/youtube-wOwhJSIr-2E.jpg', icon: 'fa-brands fa-youtube' },
  { title: 'تجاری‌سازی هوش مصنوعی و ارائه خدمات به‌صورت سرویس ابری', source: 'الکامپ', kind: 'سخنرانی', summary: 'سخنرانی تخصصی در الکامپ درباره مدل سرویس ابری، مسیر تجاری‌سازی و پیش‌نیازهای تبدیل فناوری هوش مصنوعی به خدمتی قابل ارائه.', url: 'https://www.youtube.com/watch?v=Squ-9odTru4', date: '2025-09-25', faDate: '۳ مهر ۱۴۰۴', thumbnail: '/images/media-covers/youtube-Squ-9odTru4.jpg', icon: 'fa-brands fa-youtube' },
  { title: 'جنگ بی‌صدا؛ نبرد هوش مصنوعی علیه هوش مصنوعی', source: 'رادیو تهران', kind: 'صوت', summary: 'بحث برنامه «چراغ» درباره حمله‌های هوشمند، تقابل مدل‌ها و اینکه هوش مصنوعی چگونه هم‌زمان ابزار حمله و دفاع در محیط‌های متخاصم می‌شود.', url: 'http://radiotehran.ir/videodetails/?m=100009&n=1538073', date: '2025-08-31', faDate: '۹ شهریور ۱۴۰۴', thumbnail: '/images/media-covers/radiotehran-1538073.jpg', icon: 'fa-solid fa-headphones' },
  { title: 'هوش مصنوعی، تعصب الگوریتم‌ها و تبعیض پنهان', source: 'رادیو تهران', kind: 'صوت', summary: 'گفت‌وگوی برنامه «چراغ» درباره سوگیری الگوریتمی، تبعیض دیجیتال و مسئولیت طراحان و بهره‌برداران در برابر آسیب‌های پنهان سامانه‌های هوشمند.', url: 'http://radiotehran.ir/videodetails/?m=100009&n=1530170', date: '2025-08-03', faDate: '۱۲ مرداد ۱۴۰۴', thumbnail: '/images/media-covers/radiotehran-1530170.jpg', icon: 'fa-solid fa-headphones' },
  { title: 'ربات‌های انسان‌نما و انقلاب‌های صنعتی', source: 'رادیو تهران', kind: 'صوت', summary: 'گفت‌وگو درباره جایگاه ربات‌های انسان‌نما در زنجیره تحولات صنعتی، تفاوت نمایش فناورانه با کاربرد و آینده تعامل انسان و ماشین.', url: 'http://radiotehran.ir/videodetails/?m=100009&n=1526117', date: '2025-07-21', faDate: '۳۰ تیر ۱۴۰۴', thumbnail: '/images/media-covers/radiotehran-1526117.jpg', icon: 'fa-solid fa-headphones' },
  { title: 'حکومت داده‌ها دست کیست؟', source: 'برنامه چراغ', kind: 'ویدئوی کوتاه', summary: 'بحثی درباره مالکیت، دسترسی و حکمرانی داده؛ با حضور مهران ضیابری و محمد غلامی در برنامه «چراغ» رادیو تهران.', url: 'https://www.instagram.com/reel/DL9Aa3EItyJ/', date: '2025-07-15', faDate: 'تیر ۱۴۰۴', thumbnail: '/images/media-covers/instagram-DL9Aa3EItyJ.jpg', icon: 'fa-brands fa-instagram' },
  { title: "هوش مصنوعی — ۱۰ تیر ۱۴۰۴", source: "شبکه آموزش", kind: "برنامه تلویزیونی", summary: "قسمت ۱۰ تیر ۱۴۰۴ برنامه «هوش مصنوعی» شبکه آموزش، به مدت ۳۹ دقیقه و ۲۵ ثانیه. نسخه کامل برنامه در آرشیو تلوبیون قابل مشاهده است.", url: "https://telewebion.net/episode/0x1390e156", date: "2025-07-01", faDate: "۱۰ تیر ۱۴۰۴", thumbnail: "/images/media-covers/telewebion-0x1390e156.webp", icon: "fa-solid fa-play" },
  { title: "هوش مصنوعی — ۷ تیر ۱۴۰۴", source: "شبکه آموزش", kind: "برنامه تلویزیونی", summary: "قسمت ۷ تیر ۱۴۰۴ برنامه «هوش مصنوعی» شبکه آموزش، به مدت ۴۱ دقیقه و ۴۰ ثانیه. نسخه کامل برنامه در آرشیو تلوبیون قابل مشاهده است.", url: "https://telewebion.net/episode/0x13884184", date: "2025-06-28", faDate: "۷ تیر ۱۴۰۴", thumbnail: "/images/media-covers/telewebion-0x13884184.webp", icon: "fa-solid fa-play" },
  { title: "هوش مصنوعی — ۱ تیر ۱۴۰۴", source: "شبکه آموزش", kind: "برنامه تلویزیونی", summary: "قسمت ۱ تیر ۱۴۰۴ برنامه «هوش مصنوعی» شبکه آموزش، به مدت ۳۲ دقیقه و ۴۰ ثانیه. نسخه کامل برنامه در آرشیو تلوبیون قابل مشاهده است.", url: "https://telewebion.net/episode/0x13827bfb", date: "2025-06-22", faDate: "۱ تیر ۱۴۰۴", thumbnail: "/images/media-covers/telewebion-0x13827bfb.webp", icon: "fa-solid fa-play" },
  { title: "هوش مصنوعی — ۱۴ خرداد ۱۴۰۴", source: "شبکه آموزش", kind: "برنامه تلویزیونی", summary: "قسمت ۱۴ خرداد ۱۴۰۴ برنامه «هوش مصنوعی» شبکه آموزش، به مدت ۳۱ دقیقه و ۱۸ ثانیه. نسخه کامل برنامه در آرشیو تلوبیون قابل مشاهده است.", url: "https://telewebion.net/episode/0x135012a5", date: "2025-06-04", faDate: "۱۴ خرداد ۱۴۰۴", thumbnail: "/images/media-covers/telewebion-0x135012a5.webp", icon: "fa-solid fa-play" },
  { title: "هوش مصنوعی — ۳ اردیبهشت ۱۴۰۴", source: "شبکه آموزش", kind: "برنامه تلویزیونی", summary: "قسمت ۳ اردیبهشت ۱۴۰۴ برنامه «هوش مصنوعی» شبکه آموزش، به مدت ۳۹ دقیقه و ۲۴ ثانیه. نسخه کامل برنامه در آرشیو تلوبیون قابل مشاهده است.", url: "https://telewebion.net/episode/0x12a26984", date: "2025-04-23", faDate: "۳ اردیبهشت ۱۴۰۴", thumbnail: "/images/media-covers/telewebion-0x12a26984.webp", icon: "fa-solid fa-play" },
  { title: "هوش مصنوعی — ۲۸ فروردین ۱۴۰۴", source: "شبکه آموزش", kind: "برنامه تلویزیونی", summary: "قسمت ۲۸ فروردین ۱۴۰۴ برنامه «هوش مصنوعی» شبکه آموزش، به مدت ۴۱ دقیقه و ۴۴ ثانیه. نسخه کامل برنامه در آرشیو تلوبیون قابل مشاهده است.", url: "https://telewebion.net/episode/0x128cd06f", date: "2025-04-17", faDate: "۲۸ فروردین ۱۴۰۴", thumbnail: "/images/media-covers/telewebion-0x128cd06f.webp", icon: "fa-solid fa-play" },
  { title: "هوش مصنوعی — ۱۹ فروردین ۱۴۰۴", source: "شبکه آموزش", kind: "برنامه تلویزیونی", summary: "قسمت ۱۹ فروردین ۱۴۰۴ برنامه «هوش مصنوعی» شبکه آموزش، به مدت ۴۴ دقیقه و ۱۰ ثانیه. نسخه کامل برنامه در آرشیو تلوبیون قابل مشاهده است.", url: "https://telewebion.net/episode/0x12687caa", date: "2025-04-08", faDate: "۱۹ فروردین ۱۴۰۴", thumbnail: "/images/media-covers/telewebion-0x12687caa.webp", icon: "fa-solid fa-play" },
  { title: 'آینده هوش مصنوعی', source: 'فیوتاک', kind: 'گفت‌وگوی ویدئویی', summary: 'گفت‌وگوی ۵۲ دقیقه‌ای دکتر مهدی محمدی با مهران ضیابری درباره آینده هوش مصنوعی، تجاری‌سازی، دغدغه‌های ملی و تجربه ساخت ترگمان.', url: 'https://www.youtube.com/watch?v=HO7Cawjkog8', date: '2024-12-24', faDate: '۴ دی ۱۴۰۳', thumbnail: '/images/media-covers/youtube-HO7Cawjkog8.jpg', icon: 'fa-brands fa-youtube' },
  { title: 'هوش مصنوعی چه مشاغلی را از بین می‌برد؟', source: 'کارگاه', kind: 'پادکست', summary: 'گفت‌وگوی ۸۶ دقیقه‌ای درباره آینده کار، مشاغل در معرض تغییر و مرز میان جایگزینی انسان و تغییر شکل مهارت‌ها پس از همه‌گیرشدن ChatGPT.', url: 'https://shows.acast.com/kargah/episodes/639cd492f6e39d00116bb8cd', date: '2022-12-17', faDate: '۲۶ آذر ۱۴۰۱', thumbnail: '/images/media-covers/acast-639cd492f6e39d00116bb8cd.jpg', icon: 'fa-solid fa-podcast' }
];
