import fs from 'node:fs';
import assert from 'node:assert/strict';
import test from 'node:test';
import { loadLlmModules } from './helpers/llm-modules.mjs';

const modules = await loadLlmModules();
const base = modules.guide.llmRepository, A = modules.adapters, F = modules.filtering;
const V = modules.views, R = modules.research, RV = modules['research-views'];
const d = R.enrichResearchRepository(base), rows = RV.enrichExistingRows(d, A.buildLlmViewRows(d));
const coverage = {};
const cfg=id=>V.llmViewConfigs.find(c=>c.id===id),catalog=rows['model-catalog'];
test('Repository identifiers and source references',()=>assert.deepEqual(A.validateLlmRepository(d),[]));
test('Original model coverage retained',()=>{const old=JSON.parse(fs.readFileSync('data/llm/v0.1.0/data/repository.v1.json'));assert(old.models.every(m=>d.models.some(n=>n.id===m.id)));assert.equal(d.models.length,100)});
test('All download filter results have matching packages',()=>{const out={};for(const fmt of ['ollama','gguf','onnx','safetensors','pytorch']){const found=F.filterLlmRows(catalog,cfg('model-catalog').filters,{'download-format':[fmt]},'');assert(found.every(r=>d.artifactListings.some(a=>a.modelVersionId===r.modelId&&a.format===fmt)));out[fmt]=found.length;}assert.equal(out.ollama,62);assert.equal(out.gguf,85);coverage.downloads=out;return out});
test('Faceted counts equal real results with query and other selections',()=>{const filters=cfg('model-catalog').filters,selections={'download-format':['ollama']},query='qwen';const populated=F.populateLlmFilterOptions(catalog,filters,selections,query);for(const filter of populated.filter(f=>['select','multi'].includes(f.control)))for(const option of filter.options??[]){const actual=F.filterLlmRows(catalog,populated,{...selections,[filter.id]:filter.control==='multi'?[option.value]:option.value},query).length;assert.equal(option.count,actual,`${filter.id}:${option.value}`)}});
test('Persian language search resolves Persian / فارسی / fa aliases',()=>{const filters=cfg('model-catalog').filters;const search=language=>F.filterLlmRows(catalog,filters,{language},'').map(x=>x.id).sort();assert(search('fa').length>5);assert.deepEqual(search('fa'),search('فارسی'));assert.deepEqual(search('fa'),search('Persian'));return search('fa').length});
test('Unknown factual values never satisfy numeric filters',()=>{const filters=cfg('model-catalog').filters,range=filters.find(f=>f.id==='model-size');assert(range);const small=F.filterLlmRows(catalog,filters,{'model-size':{min:'۰',max:'۲'}},'');assert(small.length>2);assert(small.every(r=>r.facets['model-size'].state==='known'&&r.facets['model-size'].canonicalNumber<=2));return small.length});
test('Software backend filters no longer depend on empty deployment experiments',()=>{const software=rows['software-products'];const key=cfg('software-products').filters.find(f=>f.id.includes('backend')).id;const all=software.filter(r=>(Array.isArray(r.facets[key])?r.facets[key]:[r.facets[key]]).some(v=>v?.state==='known'));assert.equal(all.length,17);return all.length});
test('Generative matrix contains sourced task guidance and explicit text-only input limits',()=>{const matrix=A.adaptModelUseMatrix(d);assert.equal(matrix.length,76);for(const row of matrix){const model=d.models.find(m=>m.id===row.modelId);const expected=new Set(d.modelUseGuidance.filter(use=>use.modelVersionId===model.id).map(use=>use.applicationId));if(model.inputModalities.length===1&&model.inputModalities[0]==='text')expected.add('document-vision');assert.deepEqual(Object.keys(row.matrixCells).sort(),[...expected].sort());for(const cell of Object.values(row.matrixCells)){assert.equal(cell.value.state,'known');assert(cell.sourceIds.length);}}});
test('Specialized models expose task facts and vector-memory semantics',()=>{assert.equal(rows['specialized-models'].length,24);for(const row of rows['specialized-models'])assert.equal(row.cells['vector-memory'].state,'known',row.label)});
test('Exact Ollama tags exclude cloud aliases and wrong DeepSeek lineage',()=>{const ollama=d.artifactListings.filter(a=>a.format==='ollama');assert(ollama.every(a=>!a.variant.includes('cloud')));const old=d.models.find(m=>m.exactName==='DeepSeek-R1-Distill-Llama-8B');assert(!ollama.some(a=>a.baseModelRepository==='deepseek-ai/DeepSeek-R1-Distill-Llama-8B'&&/deepseek-r1:8b(?:$|-0528)/.test(a.variant)));if(old)assert(!ollama.some(a=>a.modelVersionId===old.id&&a.variant.includes('0528')));const newer=ollama.find(a=>a.baseModelRepository==='deepseek-ai/DeepSeek-R1-0528-Qwen3-8B');assert(newer);assert(newer.variant.includes('0528'));return newer.variant});
test('Download byte sums and pinned file links',()=>{for(const a of d.artifactListings.filter(a=>a.id.startsWith('artifact-listing:v03-')&&a.format!=='ollama')){assert(a.files.length);assert(/^[a-f0-9]{40}$/.test(a.repositoryRevision));for(const f of a.files)assert(f.url.includes('/resolve/'+a.repositoryRevision+'/'));if(a.totalBytes!==undefined)assert.equal(a.totalBytes,a.files.reduce((n,f)=>n+f.bytes,0),a.id)}});
test('Memory planning changes with context and concurrency, rejects invalid context',()=>{const a=R.research.artifacts[0],p=R.calculateMemory(a,1024,1),q=R.calculateMemory(a,2048,3);assert.equal(q.kvGiB,p.kvGiB*6);assert.equal(q.weightGiB,p.weightGiB);assert.equal(R.calculateMemory(a,a.artifactContextLimitTokens+1,1),undefined);assert.equal(R.memoryStatus(30,48,2).id,'requires-sharding');assert.equal(R.memoryStatus(50,48,2).id,'over-budget')});
test('File-footprint mode covers models without applying incompatible KV formulas',()=>{const all=RV.weightFootprintRows(d,{...RV.defaultResearchControls,method:'weights'}),ids=new Set(all.map(r=>r.modelId));assert.equal(ids.size,95);for(const r of all)for(const c of Object.values(r.matrixCells))assert.equal(c.value.badge,'فقط اندازهٔ فایل');const extra=R.research.artifacts.filter(a=>a.id.startsWith('artifact:v03-plan'));assert(extra.every(a=>!['deepseek_v3','qwen3_5','mamba'].includes(a.architecture)));coverage.footprint={rows:all.length,models:ids.size};return coverage.footprint});
test('Every documented deployment route links back to a named model or existing scoped source',()=>{const routes=RV.compatibilityRows(d);assert(routes.length>=300);assert(routes.every(r=>r.sourceIds.length));const ollama=routes.filter(r=>r.facets.engine.display==='Ollama');assert.equal(ollama.length,62);coverage.deploymentRoutes=routes.length;return {routes:routes.length,ollama:ollama.length}});
test('Published result attribution preserves variants, units and unique identities',()=>{const all=d.publishedEvaluations;assert.equal(new Set(all.map(s=>s.id)).size,all.length);assert(all.every(s=>s.metric&&Number.isFinite(s.value)&&s.evidenceIds.length));assert(!all.some(s=>s.id.startsWith('published-evaluation:v03')&&s.modelVersionId.includes('gemma-3-')&&s.settings?.reportedModelColumn?.includes('PT')));const mini=all.filter(s=>s.id.startsWith('published-evaluation:v03')&&s.modelVersionId.includes('ministral-3-3b'));assert(mini.length>0);assert(mini.every(s=>s.settings.stage==='Instruct'));coverage.quality={results:all.length,models:new Set(all.map(s=>s.modelVersionId)).size};return coverage.quality});
const scores=repo=>{const model=d.models.find(m=>m.aliases.includes(repo));assert(model,repo);return d.publishedEvaluations.filter(s=>s.modelVersionId===model.id)};
test('Qwen paper columns preserve thinking and non-thinking for the same small model',()=>{const all=scores('Qwen/Qwen3-0.6B').filter(s=>s.benchmark==='AIME’24');const a=all.find(s=>s.mode==='thinking'),b=all.find(s=>s.mode==='non-thinking');assert(a&&b);assert.equal(a.value,10.7);assert.equal(b.value,3.4);assert.equal(a.settings.maxOutputTokens,38912);assert.notEqual(a.comparisonGroup,b.comparisonGroup)});
test('Gemma grounded-generation results are IT scores with a scoped RAG application',()=>{for(const [size,value]of [[4,70.1],[12,75.8]]){const s=scores(`google/gemma-3-${size}b-it`).find(s=>s.benchmark==='FACTS Grounding');assert(s);assert.equal(s.value,value);assert.equal(s.settings.checkpointStage,'instruction-tuned');assert(s.applicationIds.includes('enterprise-rag'));assert(s.settings.scope.includes('not a full retrieval pipeline'))}});
test('gpt-oss tool access and reasoning effort are separate conditions',()=>{const all=scores('openai/gpt-oss-20b');const a=all.find(s=>s.benchmark==='GPQA Diamond (no tools)'&&s.mode==='high'),b=all.find(s=>s.benchmark==='GPQA Diamond (with tools)'&&s.mode==='high');assert(a&&b);assert.equal(a.value,71.5);assert.equal(b.value,74.2);assert.equal(a.settings.tools,false);assert.equal(b.settings.tools,true);assert.equal(a.unit,'percent')});
test('Persian retrieval, mixed representations and reranking remain distinct',()=>{const all=scores('BAAI/bge-m3').filter(s=>s.benchmark==='MIRACL'&&s.language==='fa');assert.equal(all.find(s=>s.settings.representation==='Dense').value,57.7);assert.equal(all.find(s=>s.settings.representation==='All').value,60.3);const r=scores('BAAI/bge-reranker-v2-m3').find(s=>s.language==='fa');assert.equal(r.value,62.49);assert.equal(r.settings.candidateCount,100);assert.equal(r.settings.retrievalModel,'BAAI/bge-m3');assert.equal(r.metric,'published retrieval score')});
test('Published scales and embedding dimensions do not collapse into percentages',()=>{const o=scores('Qwen/Qwen3-VL-8B-Instruct').find(s=>s.benchmark==='OCRBench');assert.equal(o.value,896);assert.equal(o.unit,'score');assert.equal(o.settings.metricScale,'0..1000');const f=scores('CohereLabs/tiny-aya-global').find(s=>s.language==='fa');assert.equal(f.value,.48);assert.equal(f.unit,'score');const n=scores('nomic-ai/nomic-embed-text-v1.5').filter(s=>s.benchmark==='MTEB aggregate');assert.equal(n.length,5);assert.equal(n.find(s=>s.settings.embeddingDimensions===64).value,56.1);assert.equal(n.find(s=>s.settings.embeddingDimensions===768).value,62.28)});
test('Visible quality cells contain a sourced score and its selection conditions',()=>{const m=d.models.find(m=>m.exactName==='bge-m3');const r=rows['specialized-models'].find(r=>r.modelId===m.id),q=r.cells['published-quality'];assert.equal(q.state,'known');assert(q.display.includes('MIRACL'));assert(q.display.includes('۵۷'));assert(q.caveat.includes('فارسی'));assert(q.caveat.includes('Dense'));assert(q.evidenceIds.length);assert.equal(q.canonicalNumber,undefined)});
test('All performance groups and relevant metrics are accessible',()=>{const ids=new Set();for(const group of Object.keys(RV.performanceGroups))for(const metric of Object.keys(RV.performanceMetrics))for(const r of RV.performanceRows(d,group,metric))ids.add(r.id);assert.equal(ids.size,R.research.performance.length);coverage.performanceRuns=ids.size;return ids.size});

test('all default columns in the four main views have content and model brands are local', () => {
  for (const id of ['model-catalog', 'model-suitability', 'software-products', 'specialized-models']) {
    const config = RV.enrichExistingConfig(id === 'model-suitability' ? V.modelUseViewConfig(false) : cfg(id));
    for (const column of config.defaultColumns) for (const row of rows[id]) {
      assert.ok(row.cells[column.key], `${id}/${row.label}/${column.key}`);
      if (['license', 'introduction', 'use-condition', 'parameters'].includes(column.key)) continue;
      assert.equal(row.cells[column.key].state, 'known', `${id}/${row.label}/${column.key}`);
    }
  }
  for (const model of d.models) {
    const brand = modules.brands.llmBrand(model.familyId);
    assert.ok(brand?.startsWith('/images/'), model.familyId);
    assert.ok(fs.existsSync('static' + brand), brand);
  }
  assert.equal(modules.guide.llmGuideCollection.status, 'draft');
});
