import apiTariffs from '../../../data/llm/api-tariffs.json';
import costExample from '../../../data/llm/cost-example.fa.json';
import type { LlmLocale } from './i18n/runtime';
import { hasSource,needsRetrieval,wizardLanguages,isLocal,usesTools,positive,localized,wizardQuestions,type WizardAnswers,type AnswerStatus } from './wizard-core';
export interface WizardDecision {
 id:string;area:'solution'|'model'|'retrieval'|'deployment'|'capacity'|'cost'|'acceptance'|'operations';conclusion:string;because:string[];answerIds:string[];evidenceIds:string[];status:'supported'|'conditional'|'needs-input'|'not-feasible';assumptions:string[];nextAction?:string;
}
export function decideWizard(a:WizardAnswers,locale:LlmLocale,statuses:Record<string,AnswerStatus>={}){
 const L=(fa:string,en:string,es:string)=>localized([fa,en,es],locale),n=new Intl.NumberFormat(locale==='fa'?'fa-IR':locale,{maximumFractionDigits:2});
 const decisions:WizardDecision[]=[];
 function add(id:string,area:WizardDecision['area'],answerIds:string[],text:string[],status:WizardDecision['status']='supported',because:string[]=[],assumptions:string[]=[],evidenceIds:string[]=[]){const d={id,area,answerIds,conclusion:localized(text,locale),status,because,assumptions,evidenceIds};decisions.push(d);return d;}
 const retrieval=needsRetrieval(a),long=a.inputSize==='long',translation=a.task==='writing'&&a.writingTask==='translation';
 if(translation)add('translation-route','solution',['writingTask','sources','archiveRole','inputSize'],[long?'ترجمه را بخش‌به‌بخش انجام دهید و واژه‌نامه و جمله‌های مجاور را همراه هر بخش نگه دارید. در پایان، ترتیب بندها، عددها و یکدستی اصطلاحات را روی کل سند بررسی کنید.':'متن را با زبان مبدأ و مقصد مشخص به مترجم بدهید؛ ترجمهٔ هر بند باید با همان بند از متن اصلی قابل مقایسه باشد.','Translate with explicit source and target languages. For long documents, retain terminology and neighboring context per segment, then check order and consistency across the full document.','Traduzca con origen y destino explícitos. En documentos largos, conserve terminología y contexto por segmento y compruebe el orden y la coherencia global.']);
 else if(a.task==='writing'&&a.writingTask==='summary')add('summary-route','solution',['writingTask','sources','inputSize'],['برای هر سند، نکات اصلی را استخراج و خلاصه کنید؛ سپس خلاصهٔ مجموعه را از همین نتایج بسازید و موارد حذف‌شده را با اصل اسناد تطبیق دهید.','Summarize each document, then synthesize the collection and check omissions against the originals.','Resuma cada documento, sintetice la colección y contraste las omisiones con los originales.']);
 else if(!retrieval&&!usesTools(a))add('direct','solution',['task','sources','inputSize'],['آزمایش را با چند ورودی واقعی و خروجی مرجع همان کار شروع کنید. نتیجهٔ هر مدل را با همان نمونه‌ها مقایسه کنید.','Start with real task inputs and reference outputs; compare every model on the same examples.','Empiece con entradas reales y salidas de referencia; compare los modelos con los mismos ejemplos.']);
 if(a.task==='writing'&&hasSource(a,'archive')&&(!a.archiveRole||a.archiveRole==='unknown'))add('archive-role','solution',['archiveRole'],['خود فایل‌های آرشیو را ترجمه یا خلاصه می‌کنید، یا آرشیو فقط مرجع اصطلاحات است؟ فعلاً مسیر پردازش فایل‌ها در نظر گرفته شده است.','Are archive files the task input or reference material? The provisional path processes the files.','¿Los archivos son entrada o referencias? La ruta provisional procesa los archivos.'],'needs-input');
 if(a.task==='writing'&&hasSource(a,'archive'))add('archive-files','solution',['sources','archiveRole','writingTask'],[a.archiveRole==='reference'?'آرشیو در این مسیر مرجع اصطلاحات و متن‌های مشابه است؛ بخش‌های مرتبط را به ورودی کار اضافه کنید.':'فایل‌های آرشیو را در یک صف پردازش کنید، پیشرفت هر فایل را ذخیره کنید و خروجی‌ها را با شناسهٔ سند اصلی نگه دارید.',a.archiveRole==='reference'?'Use retrieval as terminology/reference support for the selected operation.':'Process archive files with a resumable queue and document-linked outputs.',a.archiveRole==='reference'?'Use la búsqueda como apoyo terminológico para la operación elegida.':'Procese los archivos con una cola reanudable y salidas vinculadas al documento.']);
 if(retrieval)add('archive','solution',['sources','task','archiveRole'],[a.task==='writing'?'متن مرجع را از آرشیو پیدا کنید و همراه متن اصلی به مدل بدهید.':'برای هر درخواست، بخش‌های مرتبط و مجاز اسناد را بازیابی کنید و کنار ورودی مدل بگذارید؛ پاسخ مستند باید به همان بخش‌ها ارجاع بدهد.','Retrieve relevant, permitted passages as supporting context; document answers must cite those passages.','Recupere fragmentos pertinentes y permitidos como contexto; las respuestas documentales deben citarlos.']);
 if(usesTools(a))add('connected','solution',['task','sources','codingMode'],['درخواست را به ابزار مناسب وصل کنید و اطلاعات زنده را از خود سامانه بگیرید. انتخاب ابزار، ورودی آن و نتیجهٔ اجرا جدا ثبت شوند تا خطای مدل از خطای سامانه قابل تشخیص باشد.','Route to the correct tool and retrieve live facts from the system; log tool selection, arguments and execution separately.','Dirija la solicitud a la herramienta correcta y obtenga datos del sistema; registre herramienta, argumentos y ejecución por separado.']);
 if(long&&!translation&&a.writingTask!=='summary')add('long-operation','solution',['task','inputSize'],['ورودی بلند را متناسب با همین کار بخش‌بندی کنید؛ شناسه‌ها، وابستگی‌ها و وضعیت انجام کار را میان بخش‌ها نگه دارید. طولانی‌بودن متن، هدف کار را تغییر نمی‌دهد.','Partition long input for the selected operation, preserving identifiers, dependencies and execution state.','Divida la entrada larga según la operación, conservando identificadores, dependencias y estado.']);
 if(a.task==='writing'&&a.writingTask==='translation')add('translation','acceptance',['writingTask','sourceLanguage','outputLanguage'],['ترجمهٔ هر مدل را بندبه‌بند با اصل متن مقایسه کنید: چیزی از معنی کم یا به آن اضافه نشده باشد، عددها و نام‌ها درست بمانند و اصطلاحات در سراسر متن یکسان ترجمه شوند.','Compare translations segment by segment: omissions, added meaning, numbers, names and terminology consistency distinguish candidates.','Compare traducciones por segmento: omisiones, añadidos, cifras, nombres y coherencia terminológica distinguen candidatos.']);
 if(a.task==='writing'&&a.writingTask==='summary')add('summary','acceptance',['writingTask','inputSize'],['پیش از مقایسهٔ خلاصه‌ها، نکاتی را که نباید حذف شوند مشخص کنید. ببینید هر مدل چند نکته را جا انداخته و آیا مطلبی نوشته که در اصل سند نبوده است.','Define required facts per section; measure their coverage and unsupported claims rather than brevity alone.','Defina hechos obligatorios por sección; mida cobertura y afirmaciones sin respaldo, no solo brevedad.']);
 if(a.task==='writing'&&['writing','rewriting'].includes(a.writingTask))add('style','acceptance',['writingTask','output'],['چند نمونه از نثر دلخواهتان را به مدل‌ها بدهید. سپس ببینید برای قابل استفاده‌شدن خروجی هر مدل چقدر ویرایش لازم است و کدام خواسته‌های شما را رعایت نکرده است.','Use examples of wanted and unwanted style; record editor revisions and instruction adherence for each model.','Use ejemplos del estilo deseado e indeseado; registre correcciones y cumplimiento de instrucciones por modelo.']);
 if(a.task==='extraction'||a.output==='fields')add('schema','acceptance',['task','output'],['نام فیلدها، نوع مقدار و قالب تاریخ را با کد بررسی کنید. سند ناقص هم در نمونه‌ها بگذارید؛ اگر مبلغ یا تاریخی در سند نیست، مدل باید آن را خالی بگذارد، نه اینکه حدس بزند.','Validate field schemas and types outside the model; test missing fields, numbers, dates and incomplete documents. Missing values must stay empty.','Valide esquemas y tipos fuera del modelo; pruebe campos ausentes, cifras, fechas y documentos incompletos. Los valores ausentes deben quedar vacíos.']);
 if(a.task==='coding')add('code-tests','acceptance',['codingMode','codeScope','codeLanguages'],[a.codeScope==='repository'?'دستیار را روی شاخه‌ای جدا از پروژه امتحان کنید. یک تغییر واقعی که چند فایل را درگیر می‌کند به آن بسپارید و آزمون‌های پروژه را اجرا کنید. برگشت به نسخهٔ قبلی را هم امتحان کنید.':'کد پیشنهادی را در خود پروژه اجرا کنید و آزمون‌ها را بگذرانید؛ بررسی کنید مشکلی را حل کرده و خطای تازه‌ای نساخته باشد.',a.codeScope==='repository'?'Use an isolated branch and real repository tests; include multi-file edits, dependencies and rollback in acceptance.':'Run tests in the project language; accepting a code suggestion is not itself success.',a.codeScope==='repository'?'Use una rama aislada y pruebas reales; incluya cambios en varios archivos, dependencias y reversión.':'Ejecute pruebas en el lenguaje del proyecto; aceptar texto de código no basta.']);
 if(a.format==='scan')add('scan-routes','solution',['format'],['دو مسیر را با همان صفحات مقایسه کنید: OCR و مدل متنی، یا خواندن مستقیم تصویر با مدل بینایی. خطای جدول، ترتیب خواندن و عدد را جدا بشمارید.','Compare OCR plus a text model against direct vision on the same pages; count table, reading-order and numeric errors separately.','Compare OCR más modelo textual con visión directa en las mismas páginas; cuente errores de tablas, orden y cifras por separado.']);
 if(retrieval){
  add('index','retrieval',['archiveSize','sources'],[positive(a.archiveSize)&&Number(a.archiveSize)>10000?'آماده‌سازی این تعداد سند را در چند نوبت انجام دهید و پیشرفت کار را ذخیره کنید تا پس از قطع اجرا مجبور نباشید از ابتدا شروع کنید. برای هر بخش، سند اصلی و نسخهٔ مدل embedding را نگه دارید.':'برای شروع، چند سند از هر نوع انتخاب کنید. همان سؤال‌ها را یک‌بار با جست‌وجوی کلمه و یک‌بار با embedding امتحان کنید و ببینید کدام، بخش درست سند را بهتر پیدا می‌کند.',positive(a.archiveSize)&&Number(a.archiveSize)>10000?'Use resumable batch ingestion; track document, chunk and embedding revisions to rebuild the index.':'Start with a representative document subset and lexical retrieval as the embedding baseline.',positive(a.archiveSize)&&Number(a.archiveSize)>10000?'Use ingesta por lotes reanudable; registre versiones de documentos, fragmentos y embeddings para reconstruir el índice.':'Empiece con documentos representativos y búsqueda léxica como base para embeddings.']);
  add('refresh-'+(a.freshness??'unknown'),'retrieval',['freshness'],[a.freshness==='daily'?'جست‌وجو را هر روز با تغییرات اسناد به‌روز کنید. اگر سندی حذف یا اصلاح شد، بررسی کنید متن قدیمی دیگر در پاسخ‌ها استفاده نشود.':a.freshness==='rare'?'چون اسناد به‌ندرت تغییر می‌کنند، جست‌وجو را هنگام انتشار نسخهٔ تازه به‌روز کنید؛ لازم نیست هر روز همهٔ اسناد دوباره پردازش شوند.':'زمان به‌روزرسانی جست‌وجو را با تغییر اسناد هماهنگ کنید. فقط بخش‌های تازه و تغییرکرده را دوباره به embedding تبدیل کنید.',a.freshness==='daily'?'Update the index daily for changes and deletions; monitor embedding jobs, revisions and stale-chunk removal.':a.freshness==='rare'?'Rebuild affected index entries when documents are released; continuous archive processing is unnecessary.':'Align index refresh with document releases; freshness affects embedding work.',a.freshness==='daily'?'Actualice a diario cambios y borrados; supervise embeddings, versiones y retirada de fragmentos antiguos.':a.freshness==='rare'?'Actualice el índice al publicar documentos; no hace falta procesar continuamente el archivo.':'Ajuste la actualización del índice a la publicación documental.'],a.freshness&&a.freshness!=='unknown'?'supported':'needs-input');
  if(a.access==='roles')add('permissions','retrieval',['access'],['جست‌وجو برای هر کاربر فقط در اسنادی انجام شود که اجازهٔ دیدنشان را دارد. پس از لغو دسترسی، متن سند نباید از حافظهٔ موقت یا پاسخ‌های ذخیره‌شده دوباره در اختیار او قرار بگیرد.','Store permissions with chunks and filter by user identity before retrieval and prompt assembly. Role changes and revocations must cover indexes and caches.','Guarde permisos con los fragmentos y filtre por identidad antes de recuperar y construir la entrada. Aplique revocaciones también a índices y cachés.']);
  add('reranking','retrieval',['existing','failure'],[a.failure==='ranking'?'چون سند درست پیدا می‌شود ولی پایین فهرست می‌ماند، همان جست‌وجو را با و بدون reranker مقایسه کنید. ببینید بهبود رتبهٔ سند چقدر به زمان پاسخ اضافه می‌کند.':a.failure==='missing'?'اول استخراج متن و بازیابی را اصلاح کنید؛ بازچینش سندی را که اصلاً پیدا نشده وارد فهرست نمی‌کند.':'فعلاً بدون reranker شروع کنید. اگر سند درست پیدا شد ولی پایین فهرست ماند، بازچینش نتایج را امتحان کنید.',a.failure==='ranking'?'A/B test a reranker because relevant documents rank low; measure added latency.':a.failure==='missing'?'Fix extraction and retrieval first; reranking cannot recover a missing candidate.':'Keep reranking optional until correct documents are found but poorly ranked.',a.failure==='ranking'?'Pruebe reordenación A/B porque los documentos relevantes quedan abajo; mida la latencia añadida.':a.failure==='missing'?'Corrija extracción y búsqueda; reordenar no recupera candidatos ausentes.':'Mantenga la reordenación opcional hasta detectar documentos correctos mal posicionados.'],'conditional');
 }
 const active=positive(a.concurrency),users=positive(a.users);
 if(active&&(!a.loadDefinition||a.loadDefinition==='unknown')&&(active>1||users&&active>users))add('load-definition','capacity',['users','concurrency','loadDefinition'],['از این تعداد درخواست هم‌زمان، چند مورد باید فوراً پردازش شوند و چند مورد می‌توانند در صف بمانند؟ برای حساب‌کردن حافظه، تعداد درخواست‌های در حال پردازش را لازم داریم.','Does concurrency mean active requests or jobs submitted to a queue? Do systems also submit work? This changes memory and queue planning.','¿Son solicitudes activas o trabajos enviados a cola? ¿También envían trabajo otros sistemas? Esto cambia memoria y planificación.'],'needs-input');
 if(active&&active>1)add('central-service','capacity',['concurrency','loadDefinition','mode'],[a.loadDefinition==='queued'?'درخواست‌ها را در صفی نگه دارید که با قطع سرویس از بین نرود و تعداد پردازش‌های هم‌زمان را محدود کنید. زمان انتظار در صف را جدا از زمان ساخت پاسخ ثبت کنید.':'مدل را به‌صورت یک سرویس مشترک راه‌اندازی کنید. درخواست‌ها را هم‌زمان بفرستید و زمان پاسخ را بسنجید؛ اگر صف بیش از مهلت قابل قبول طول می‌کشد، ظرفیت یا تعداد نمونه‌های در حال اجرا را افزایش دهید.',a.loadDefinition==='queued'?'Use a central service with a durable queue and an active-job limit. Measure queue waiting separately from generation.':'Use central admission control; test simultaneous arrivals, queues and slowdown. Determine replica count from measured load tests.',a.loadDefinition==='queued'?'Use servicio central con cola persistente y límite de tareas activas. Mida espera aparte de generación.':'Use admisión central controlada; pruebe llegadas simultáneas, colas y degradación. Determine réplicas mediante pruebas.']);
 if(users&&users>100)add('user-management','operations',['users','audience'],['از همین مرحله برای کاربران حساب جدا، سقف مصرف و گزارش استفاده در نظر بگیرید تا استفادهٔ سنگین یک گروه باعث معطل‌شدن بقیه نشود.','Include identity, group quotas and usage reporting in the central pilot; employee count alone does not size GPUs.','Incluya identidad, cuotas y consumo por grupo en el piloto central; el número de empleados no determina las GPU.']);
 if(active&&active>128&&a.loadDefinition!=='queued')add('memory-domain','capacity',['concurrency'],['محاسبه‌گر این صفحه تا ۱۲۸ درخواست فعال را بررسی می‌کند. برای تعداد بیشتر، ظرفیت هر نمونه و تقسیم درخواست‌ها بین چند نمونه را با آزمون بار اندازه بگیرید.','This active load is outside the memory calculator. Fit is unverified; measure per-replica capacity and queueing separately.','Esta carga activa supera el calculador. No se ha verificado la memoria; mida capacidad por réplica y colas.'],'needs-input');
 const batch=positive(a.batchCount)&&positive(a.deadline)?{itemsPerHour:Number(a.batchCount)/Number(a.deadline),secondsPerCompletion:Number(a.deadline)*3600/Number(a.batchCount)}:undefined;
 if(batch)add('batch-rate','capacity',['batchCount','deadline','batchFrequency','offPeak'],[`برای پایان به‌موقع، کل سرویس باید حداقل ${n.format(batch.itemsPerHour)} مورد در ساعت تمام کند؛ یعنی در مجموع یک نتیجه در هر ${n.format(batch.secondsPerCompletion)} ثانیه. در آزمایش بررسی کنید سرویس به این تعداد می‌رسد یا نه.`,`The service must complete at least ${n.format(batch.itemsPerHour)} items/hour: one completion every ${n.format(batch.secondsPerCompletion)} seconds in aggregate. This is required throughput, not a model measurement.`,`El servicio debe completar al menos ${n.format(batch.itemsPerHour)} elementos/hora: uno cada ${n.format(batch.secondsPerCompletion)} segundos en total. Es la tasa necesaria, no una medición del modelo.`]);
 if(a.offPeak==='yes')add('off-peak','operations',['offPeak','batchFrequency'],['پردازش دسته‌ای را به ساعت‌های خلوت ببرید. اگر کاربر درخواست فوری فرستاد، بخشی از ظرفیت برای او آزاد بماند و پردازش نیمه‌تمام بعداً ادامه پیدا کند.','Schedule batch jobs off-peak while reserving interactive capacity; make interrupted jobs resumable.','Programe lotes fuera de horas punta, reserve capacidad interactiva y permita reanudar trabajos.']);
 if(positive(a.fullResponse))add(Number(a.fullResponse)<=10?'tight-latency':'latency-headroom','capacity',['fullResponse','firstResponse','outputTokens'],[Number(a.fullResponse)<=10?'برای پاسخ کامل در حداکثر ده ثانیه، حالت بدون استدلال طولانی مدل را هم امتحان کنید. طول پاسخ و انتظار در صف را محدود کنید و ببینید این تغییرها کیفیت پاسخ را پایین می‌آورند یا نه.':'با این فرصت بیشتر، می‌توانید مدل‌های استدلالی و پاسخ‌های مفصل‌تر را هم مقایسه کنید. زمان شروع پاسخ و زمان کامل‌شدن آن را جدا اندازه بگیرید.',Number(a.fullResponse)<=10?'For a full answer within ten seconds, compare non-thinking execution, output limits and queue delay separately; retain quality acceptance.':'The longer deadline allows comparison of reasoning and longer output; measure first response and full-response percentiles separately.',Number(a.fullResponse)<=10?'Para responder en diez segundos, compare ejecución sin razonamiento, límites de salida y espera; mantenga los criterios de calidad.':'El plazo mayor permite comparar razonamiento y salidas más largas; mida primera respuesta y percentiles por separado.'],'conditional');
 if(isLocal(a)){
  if(a.hardware==='none')add('provision-pilot','deployment',['hardware','deployment','capex','monthly'],['چون فعلاً دستگاهی ندارید، آزمایش را با تجهیزات قرضی یا اجاره‌ای شروع کنید. با اندازه‌گیری حافظه و زمان پاسخ مشخص می‌شود برای استفادهٔ روزمره چه سیستمی لازم دارید.','Provision a temporary host or trial equipment for the pilot. Price production hardware after memory and speed tests; no existing device was declared.','Consiga un equipo de prueba o alojamiento temporal. Presupueste producción después de medir memoria y velocidad; no se declaró equipo existente.'],'conditional');
  else if(!a.hardware||a.hardware==='unknown')add('inspect-equipment','deployment',['hardware','deployment'],['مشخصات دستگاه در دسترس و حافظهٔ آزاد آن را وارد کنید تا بتوانیم پیشنهاد اجرا را دقیق‌تر کنیم.','Confirm whether a host exists and its free memory before choosing the pilot host; neither new procurement nor fit is established.','Confirme si existe equipo y su memoria libre antes del piloto; no se ha determinado compra ni compatibilidad.'],'needs-input');
  else add('existing-pilot','deployment',['hardware','ram','vram','gpuName','gpuCount','shared','upgrade'],[a.hardware==='cpu'?'ابتدا مدل را روی CPU موجود با یک درخواست امتحان کنید. اگر زمان پاسخ برایتان مناسب بود، تعداد درخواست‌ها را کم‌کم افزایش دهید.':'هر مدل را جداگانه روی کارت فعلی امتحان کنید. اگر چند کارت دارید، اجرای یک نمونه روی هر کارت را با تقسیم یک مدل بین کارت‌ها مقایسه کنید؛ تقسیم مدل به پشتیبانی نرم‌افزار و اتصال کارت‌ها نیاز دارد.',a.hardware==='cpu'?'Start a single-user CPU pilot with a small package; measured latency determines whether to continue.':'Test candidates separately on the existing GPU. Do not add device memories without verifying model sharding and interconnect support.',a.hardware==='cpu'?'Empiece un piloto monousuario en CPU con un paquete ligero; la latencia medida determina la continuación.':'Pruebe candidatos por separado en la GPU existente. No sume memorias sin verificar partición y conexiones.'],'conditional');
 }else add('service-pilot','deployment',['policy','deployment','serviceAccess'],[a.policy==='public'?'از ارائه‌دهنده بپرسید کدام نسخهٔ این مدل‌ها را ارائه می‌کند و همان نسخه را با نمونه‌های کارتان امتحان کنید.':'محل مجاز پردازش اطلاعات را مشخص کنید. تا آن زمان، برای آزمایش API از نمونه‌ای استفاده کنید که اطلاعات محرمانه ندارد.',a.policy==='public'?'Compare a managed-service pilot using an accessible model revision; catalog presence does not guarantee an API endpoint.':'Until processing boundaries are established, do not send task data to a public API. Non-sensitive examples can test the technical path.',a.policy==='public'?'Compare un piloto gestionado con una versión accesible; aparecer en el catálogo no garantiza API.':'Hasta definir límites de procesamiento, no envíe datos a API pública. Ejemplos no sensibles permiten probar la vía técnica.'],a.policy==='public'?'conditional':'needs-input');
 if(a.serviceAccess==='limited')add('restricted-access','deployment',['serviceAccess'],['چون دسترسی به سرویس محدود است، اجرای مدل روی تجهیزات خودتان یا استفاده از ارائه‌دهنده‌ای با دسترسی پایدار را بررسی کنید.','Do not make delivery depend on an unreliable external API; assess an accessible in-boundary service or self-hosting.','No dependa de una API externa poco accesible; evalúe servicio permitido accesible o alojamiento propio.'],'conditional');
 add('production','operations',['phase','availability','owner'],[a.availability==='always'||a.availability==='critical'?'برای قطعی دستگاه، میزبان جایگزین در نظر بگیرید. در آزمایش، یک میزبان را از دسترس خارج کنید و ببینید بقیه می‌توانند پاسخ‌ها را در زمان قابل قبول تحویل بدهند یا نه.':'پیش از استفادهٔ روزمره، ثبت خطا و هشدار طولانی‌شدن صف را راه‌اندازی کنید. نسخهٔ قبلی مدل و تنظیمات را نگه دارید تا اگر به‌روزرسانی مشکل ایجاد کرد، بتوانید برگردید.',a.availability==='always'||a.availability==='critical'?'Production needs queue monitoring, failover hosting and failure tests. Measure capacity with a host unavailable.':'Production needs error and queue monitoring, rollback versions and an accountable operator; a pilot configuration is not an SLA.',a.availability==='always'||a.availability==='critical'?'Producción necesita supervisión de colas, respaldo y pruebas de fallos. Mida capacidad sin un servidor.':'Producción necesita supervisión de errores y colas, reversión y responsable; la configuración piloto no es un SLA.'],'conditional');
 if(a.owner==='none'||a.owner==='provider')add('managed-operations','operations',['owner','deployment'],['در قرارداد مشخص کنید چه کسی خطاها را پیگیری می‌کند، به‌روزرسانی و پشتیبان‌گیری را انجام می‌دهد و هنگام قطعی چقدر فرصت رسیدگی دارد. دسترسی‌های مدیریتی هم باید به سازمان تحویل داده شوند.','Contract managed operations: monitoring, patches, backups, response times and access handover need a named owner.','Contrate operación gestionada: supervisión, parches, copias, tiempos de atención y entrega de accesos necesitan responsable.']);
 else if(a.owner==='experienced')add('internal-operations','operations',['owner'],['تیم شما تنظیمات نصب و نسخهٔ مدل و نرم‌افزار را ثبت کند تا راه‌اندازی دوباره روی دستگاه دیگر ممکن باشد. هر به‌روزرسانی را پیش از جایگزینی سرویس فعال امتحان کنید.','Have the internal team own pinned versions, repeatable deployment, monitoring and rollback; test upgrades before replacement.','El equipo interno debe controlar versiones, despliegue reproducible, supervisión y reversión; pruebe actualizaciones antes de sustituir.']);
 else if(a.owner==='new')add('training-handover','operations',['owner'],['برای تیم تازه‌کار، آموزش راه‌اندازی و رفع خطا را هم در برنامه بگذارید. تیم باید در عمل بتواند نسخهٔ پشتیبان را برگرداند و یک به‌روزرسانی ناموفق را لغو کند.','Pair a simpler pilot runtime with hands-on handover; the new team should restore backups and roll back a version itself.','Combine un motor sencillo con formación práctica; el equipo nuevo debe restaurar copias y revertir versiones.']);
 if(usesTools(a)){
  add('tool-connection-'+(a.connection??'unknown'),'solution',['connection'],[a.connection==='ui'?'اگر تنها راه اتصال، کار با صفحهٔ نرم‌افزار است، به ابزار کنترل مرورگر یا دسکتاپ نیاز دارید. تغییر ظاهر صفحه را هم امتحان کنید؛ ممکن است مدل تصمیم درستی بگیرد ولی ابزار دکمهٔ اشتباهی را بزند.':'برای هر ابزار مشخص کنید چه ورودی‌هایی می‌گیرد، چه خطاهایی برمی‌گرداند و چقدر فرصت اجرا دارد. دسترسی پایگاه داده را در خود ابزار محدود کنید، نه فقط در دستور متنی مدل.',a.connection==='ui'?'UI-only integration requires browser/desktop automation, a restricted account and layout-change tests; separate tool failures from model errors.':'Implement tool schemas, error responses and timeouts; constrain queries and permissions in the database tool layer.',a.connection==='ui'?'La integración solo por interfaz requiere automatización, cuenta limitada y pruebas de cambios de pantalla; separe fallos de herramienta y modelo.':'Implemente esquemas, errores y plazos; limite consultas y permisos en la capa de herramientas.'],a.connection&&a.connection!=='unknown'?'supported':'needs-input');
  add('authority-'+(a.authority??'unknown'),'acceptance',['authority'],[a.authority==='read'?'حساب اتصال و ابزارها فقط اجازهٔ خواندن داشته باشند. در آزمایش از دستیار بخواهید چیزی را تغییر بدهد و بررسی کنید که درخواست واقعاً رد می‌شود.':a.authority==='approval'?'پیش از هر تغییر، جزئیات آن را به کاربر نشان دهید و تأیید بگیرید. تأیید یک سفارش نباید اجازهٔ ثبت سفارش متفاوتی بدهد؛ فرستادن دوبارهٔ همان درخواست هم نباید دو سفارش بسازد.':a.authority==='bounded'?'سقف مبلغ، تعداد عملیات و اختیار دستیار را در کد کنترل کنید. امکان توقف فوری هم بگذارید و در آزمایش بررسی کنید که دستور مدل نمی‌تواند از این محدودیت‌ها عبور کند.':'فعلاً دستیار فقط پیشنهاد بدهد. پس از مشخص‌شدن حدود اختیار، اجازهٔ انجام عملیات را به آن بدهید.',a.authority==='read'?'Issue read-only tools and tokens; mutation requests must be rejected and logged before execution.':a.authority==='approval'?'Require an exact preview and human approval before mutations; bind approval to parameters and prevent duplicate execution.':a.authority==='bounded'?'Enforce action limits and an emergency stop outside the model; reject out-of-scope and repeated actions in tests.':'Keep agent outputs advisory until authority is specified; do not grant mutation access.',a.authority==='read'?'Use herramientas y credenciales de lectura; rechace y registre cambios antes de ejecutarlos.':a.authority==='approval'?'Exija vista previa y aprobación vinculada a parámetros; impida ejecuciones duplicadas.':a.authority==='bounded'?'Aplique límites y parada de emergencia fuera del modelo; rechace acciones fuera de alcance o repetidas.':'Mantenga salidas como propuestas hasta definir autoridad; no conceda permisos de cambio.']);
 }
 for(const success of (a.success??'').split('|')){
 const checks:Record<string,string[]>={exact:['عددها و نام‌ها را با متن اصلی تطبیق دهید. تعداد موارد نادرست و مطالبی را که مدل از خودش اضافه کرده جدا بشمارید.','Check numbers, names and unsupported claims against references; report each error rate separately.','Compare cifras, nombres y afirmaciones con referencias; informe cada tipo de error.'],editing:['زمان اصلاح انسانی و تعداد اصلاح‌های ضروری را در کار فعلی و خروجی هر مدل مقایسه کنید.','Compare human editing time and required corrections against the existing workflow.','Compare tiempo de edición y correcciones necesarias con el flujo actual.'],cited:['لینک یا بند سند را که مدل برای پاسخ آورده باز کنید و ببینید واقعاً همان پاسخ را تأیید می‌کند یا نه.','Verify supporting passages and attribution per answer; separate unsupported from grounded answers.','Verifique fragmentos de apoyo y atribución; separe respuestas sin respaldo.'],fields:['خروجی را با فیلدها و مقدارهای درست مقایسه کنید. مواردی را که مدل برای فیلد خالی مقداری ساخته، جدا بشمارید.','Validate schema and reference values, counting missing-field errors separately.','Valide esquema y valores de referencia, contando campos ausentes aparte.'],tests:['قبولی آزمون واقعی و تغییر ناخواسته در فایل‌های دیگر را بسنجید.','Measure real test passes and unintended edits elsewhere.','Mida pruebas reales superadas y cambios no deseados.'],tools:['بررسی کنید دستیار ابزار درست را با ورودی درست اجرا کرده باشد. قطع و ارسال دوبارهٔ درخواست را هم امتحان کنید تا عملیات دوبار انجام نشود.','Accept correct tool arguments, operation results and duplicate prevention.','Exija argumentos correctos, resultados y prevención de duplicados.'],latency:['با تعداد درخواست موردنظرتان، زمان انتظار در صف، شروع پاسخ و پایان پاسخ را اندازه بگیرید. علاوه بر زمان میانه، زمانی را گزارش کنید که ۹۵ درصد درخواست‌ها تا آن موقع تمام شده‌اند.','Record queue, first-response and full-response latency at p50/p95 under target load.','Registre cola, primera respuesta y respuesta completa en p50/p95 bajo carga objetivo.']};if(checks[success])add('success-'+success,'acceptance',['success'],checks[success]);}
 if(a.risk==='direct'||a.risk==='decision')add('release-gate','acceptance',['risk'],['سؤال‌هایی را هم امتحان کنید که اطلاعات کافی برای پاسخشان وجود ندارد. مدل باید به‌جای ساختن پاسخ، موضوع را به فرد مسئول بسپارد؛ به‌خصوص وقتی پاسخ مستقیم به مشتری می‌رسد یا مبنای تصمیم مهمی است.','Before direct delivery or sensitive decisions, gate release on incorrect-answer and refusal tests; route uncertain cases to humans and provide a stop mechanism.','Antes de entrega directa o decisiones sensibles, exija pruebas de errores y abstención; derive casos dudosos a personas y permita detener el servicio.']);
 else if(a.risk==='review')add('review-workflow','acceptance',['risk'],['خروجی پیش‌نویس بماند و تأیید ویراستار ثبت شود؛ کیفیت را با زمان رسیدن به نسخهٔ تأییدشده بسنجید.','Keep output as a draft with recorded reviewer approval; measure time to an accepted version.','Mantenga borradores con aprobación registrada; mida tiempo hasta versión aceptada.']);
 if(a.threshold&&a.threshold!=='unknown')add('threshold-confirmation','acceptance',['threshold'],['توضیحی را که دربارهٔ نتیجهٔ قابل قبول داده‌اید، با تیم اجرا مرور کنید. چند نمونهٔ قبول و رد آماده کنید و توافق کنید در چند نمونه از کل آزمون، این نتیجه باید به دست بیاید.','Turn the free-text criterion into an agreed measurement, test set and acceptance threshold; it has not been parsed as a contractual number.','Convierta el criterio libre en medición, conjunto de prueba y umbral acordados; no se ha interpretado como cifra contractual.'],'needs-input');
 const totalToman=costExample.parts.reduce((s,p)=>s+p.amountToman,0);
 const costComparison=a.currency==='million-toman'&&a.capex!==undefined&&a.capex!=='unknown'?{exampleToman:totalToman,budgetToman:Number(a.capex)*1e6,withinBudget:Number(a.capex)*1e6>=totalToman,dates:[...new Set(costExample.parts.map(p=>p.sourcePriceDate))],sourceUrls:costExample.parts.map(p=>p.sourceUrl)}:undefined;
 if(costComparison&&a.hardware==='none')add(costComparison.withinBudget?'purchase-example-covered':'purchase-example-shortfall','cost',['capex','currency','hardware'],[`نمونهٔ قیمت‌گذاری‌شدهٔ سیستم کامل 4090 با ۲۴ گیگابایت حافظه، ${n.format(totalToman/1e6)} میلیون تومان است (اقلام ۱۶ تا ۱۹ سپتامبر ۲۰۲۶). سقف خرید شما ${costComparison.withinBudget?'این نمونه را پوشش می‌دهد؛ خرید پس از آزمون بار مطرح می‌شود':'به این نمونه نمی‌رسد؛ برای پایلوت میزبان قرضی یا اجارهٔ مجاز را بررسی کنید'}. این نمونه هنوز پیکربندی تأییدشدهٔ بار شما نیست.`,`The dated complete 24GB 4090 example totals ${n.format(totalToman/1e6)} million toman (16–19 September 2026). Your capex ${costComparison.withinBudget?'covers this example; procurement follows workload tests':'does not cover it; consider borrowed or permitted rented pilot capacity'}. This is not yet a validated configuration for your workload.`,`El ejemplo completo con 4090 de 24 GB suma ${n.format(totalToman/1e6)} millones de toman (16–19 de septiembre de 2026). Su presupuesto ${costComparison.withinBudget?'cubre el ejemplo; compre tras probar la carga':'no lo cubre; considere equipo prestado o alquiler permitido'}. No es una configuración validada para su carga.`],'conditional',[],[],costComparison.sourceUrls);
 if(a.hardware==='none'&&a.capex==='0')add('no-procurement-budget','cost',['hardware','capex','monthly'],[a.monthly==='0'?'با نداشتن دستگاه و بودجهٔ صفر، فعلاً اجرای مستقل ممکن نیست. برای آزمایش باید دستگاهی قرض بگیرید یا بودجه‌ای برای اجاره در نظر بگیرید.':'چون بودجه‌ای برای خرید ندارید، آزمایش را با دستگاه قرضی یا اجاره از بودجهٔ ماهانه انجام دهید.',a.monthly==='0'?'No device or procurement/usage budget was declared; self-hosting has no funded path. Choose permitted borrowed resources, reduced scope or a budget change.':'Zero procurement budget rules out purchase; the pilot needs permitted borrowed resources or rental funded from usage budget.',a.monthly==='0'?'No hay equipo ni presupuesto de compra/uso; no existe vía financiada propia. Elija recursos prestados permitidos, menor alcance o nuevo presupuesto.':'Sin presupuesto de compra, el piloto necesita recursos prestados o alquiler cubierto por consumo.'],a.monthly==='0'?'not-feasible':'conditional');
 const days=positive(a.workdays)??22,avgIn=positive(a.averageInputTokens),avgOut=positive(a.averageOutputTokens),requests=positive(a.requests);
 const batchRuns=a.batchFrequency==='daily'?days:a.batchFrequency==='weekly'?52/12:a.batchFrequency==='monthly'?1:undefined;
 const batchItems=['batch','both'].includes(a.mode)&&positive(a.batchCount)&&batchRuns?Number(a.batchCount)*batchRuns:0;
 const interactiveItems=['interactive','both'].includes(a.mode)&&requests?requests*days:0;
 const monthlyItems=batchItems+interactiveItems;
 const monthlyTokens=monthlyItems&&avgIn&&avgOut?{input:monthlyItems*avgIn,output:monthlyItems*avgOut,days,assumedDays:!positive(a.workdays)&&(interactiveItems>0||a.batchFrequency==='daily'),items:monthlyItems,batchItems,interactiveItems,basis:'estimate' as const}:undefined;
 if(batchItems)add('batch-volume','cost',['batchCount','batchFrequency','workdays'],[`مصرف دسته‌ای این سناریو در ماه ${n.format(batchItems)} مورد است: ${n.format(Number(a.batchCount))} مورد در هر نوبت و ${n.format(batchRuns!)} نوبت در ماه.`,`Monthly batch volume is ${n.format(batchItems)} items: ${n.format(Number(a.batchCount))} per run × ${n.format(batchRuns!)} runs/month.`,`Volumen mensual: ${n.format(batchItems)} elementos; ${n.format(Number(a.batchCount))} por lote × ${n.format(batchRuns!)} lotes/mes.`],'conditional',[],[a.batchFrequency==='weekly'?L('برای تکرار هفتگی، میانگین ۵۲÷۱۲ هفته در ماه فرض شده است.','Weekly frequency assumes 52/12 weeks per month.','La frecuencia semanal supone 52/12 semanas al mes.'):L(`تکرار روزانه بر اساس ${n.format(days)} روز کاری است؛ تکرار ماهانه یک نوبت در ماه است.`,`Daily repetition uses ${n.format(days)} working days; monthly repetition is one run.`,`La repetición diaria usa ${n.format(days)} días laborables; la mensual, un lote.`)]);
 if(['batch','both'].includes(a.mode)&&positive(a.batchCount)&&!batchRuns)add('batch-frequency','cost',['batchFrequency'],['تکرار پردازش دسته‌ای را مشخص کنید تا مصرف ماهانه محاسبه شود.','Specify batch frequency to calculate monthly usage.','Indique la frecuencia para calcular el consumo mensual.'],'needs-input');
 if(monthlyTokens)add('token-volume','cost',['requests','batchCount','batchFrequency','workdays','averageInputTokens','averageOutputTokens'],[`مصرف ماهانهٔ برآوردی: ${n.format(monthlyTokens.input)} توکن ورودی و ${n.format(monthlyTokens.output)} توکن خروجی برای ${n.format(monthlyItems)} درخواست. `,`Estimated monthly usage: ${n.format(monthlyTokens.input)} input and ${n.format(monthlyTokens.output)} output tokens across ${n.format(monthlyItems)} requests. This average does not size peak load.`,`Uso mensual estimado: ${n.format(monthlyTokens.input)} tokens de entrada y ${n.format(monthlyTokens.output)} de salida para ${n.format(monthlyItems)} solicitudes. Este promedio no dimensiona picos.`],'conditional',[],monthlyTokens.assumedDays?[L('چون تعداد روزهای استفاده را ننوشته‌اید، فعلاً ۲۲ روز در ماه حساب کرده‌ایم.','Scenario assumption: 22 working days/month; not a user answer.','Supuesto: 22 días laborables/mes; no es una respuesta del usuario.')]:[]);
 add('unpriced-components','cost',['deployment','months','monthly'],[isLocal(a)?'برای مقایسهٔ خرید و اجاره، هزینهٔ ماهانهٔ میزبانی، برق و پشتیبانی را هم به مبلغ تجهیزات اضافه کنید. این هزینه‌ها به محل استقرار و قرارداد شما بستگی دارند.':'مصرف توکن را با تعرفهٔ ارائه‌دهندهٔ قابل دسترس خودتان حساب کنید. برای مقایسهٔ دو تعرفه، قیمت ورودی و خروجی و هزینهٔ ابزارهای اضافه را جدا کنار هم بگذارید.',isLocal(a)?'Hosting, power and support for this configuration remain unpriced; they are not included in the purchase example.':'The usable provider, revision and regional tariff remain unset; API cost is not calculated from budget or maximum output tokens.',isLocal(a)?'Faltan precios de alojamiento, electricidad y soporte; no están incluidos en el ejemplo de compra.':'Faltan proveedor accesible, versión y tarifa regional; el coste API no se calcula a partir del presupuesto ni del máximo de salida.'],'needs-input');
 if(requests&&positive(a.hours))add('average-arrivals','capacity',['requests','hours','traffic'],[`متوسط ورود درخواست در ساعت‌های کار ${n.format(requests/Number(a.hours))} مورد در ساعت است. ${a.traffic==='bursty'?'چون درخواست‌ها یک‌باره زیاد می‌شوند، ارسال هم‌زمان آن‌ها و زمان انتظار در صف را هم امتحان کنید.':'برای آزمایش زمان پاسخ، ساعت شلوغ را هم جدا در نظر بگیرید.'}`,`Average arrivals during working hours: ${n.format(requests/Number(a.hours))}/hour. ${a.traffic==='bursty'?'Test arrival bursts separately and size queue admission for them.':'This average does not replace peak-load testing.'}`,`Llegadas medias durante el uso: ${n.format(requests/Number(a.hours))}/hora. ${a.traffic==='bursty'?'Pruebe ráfagas aparte y planifique la admisión a cola.':'El promedio no sustituye pruebas de picos.'}`]);
 if(a.shared==='shared')add('shared-host','capacity',['shared','ram','vram'],['هنگام آزمایش، برنامه‌های دیگری را هم که معمولاً روی همین دستگاه کار می‌کنند روشن نگه دارید. زمان پاسخ و حافظهٔ آزاد را در همین شرایط بسنجید.','Test with the host’s other workloads running; idle free memory and latency are not a guaranteed allocation.','Pruebe con las otras cargas activas; memoria libre y latencia en reposo no son una asignación garantizada.']);
 if(a.currency==='million-toman'&&positive(a.usdRate)){
  const initial=a.capex!==undefined&&a.capex!=='unknown'?Number(a.capex)*1e6/Number(a.usdRate):undefined;
  const monthly=a.monthly!==undefined&&a.monthly!=='unknown'?Number(a.monthly)*1e6/Number(a.usdRate):undefined;
  if(initial!==undefined||monthly!==undefined)add('budget-conversion','cost',['currency','usdRate','capex','monthly'],[`با نرخ اعلامی هر دلار ${n.format(Number(a.usdRate))} تومان، سقف اولیه ${initial===undefined?'نامشخص':n.format(initial)+' دلار'} و سقف ماهانه ${monthly===undefined?'نامشخص':n.format(monthly)+' دلار'} است؛ `,`At your declared ${n.format(Number(a.usdRate))} toman/USD, setup limit is ${initial===undefined?'undecided':n.format(initial)+' USD'} and monthly limit ${monthly===undefined?'undecided':n.format(monthly)+' USD'}. These convert budgets, not service prices.`,`Con su cambio de ${n.format(Number(a.usdRate))} toman/USD, el límite inicial es ${initial===undefined?'pendiente':n.format(initial)+' USD'} y mensual ${monthly===undefined?'pendiente':n.format(monthly)+' USD'}. Son presupuestos convertidos, no precios.`]);
 }
 if(positive(a.months)&&costComparison)add('purchase-horizon','cost',['months','currency','capex'],[`سرشکن‌کردن فقط خریدِ نمونه در ${n.format(Number(a.months))} ماه: ${n.format(totalToman/1e6/Number(a.months))} میلیون تومان در ماه؛ برق، بهره‌برداری، هزینهٔ سرمایه و ارزش فروش در آن نیست.`,`Spreading the example purchase alone over ${n.format(Number(a.months))} months gives ${n.format(totalToman/1e6/Number(a.months))} million toman/month; excludes power, operations, financing and resale.`,`Distribuir solo la compra en ${n.format(Number(a.months))} meses da ${n.format(totalToman/1e6/Number(a.months))} millones de toman/mes; excluye electricidad, operación, financiación y reventa.`],'conditional',[],[],costComparison.sourceUrls);
 if(a.format==='media'&&(!a.mediaType||a.mediaType==='unknown'))add('media-type','solution',['mediaType'],['نوع رسانه را مشخص کنید؛ صوت به پیاده‌سازی متن و تصویر به OCR یا مدل بینایی نیاز دارد.','Specify media type: audio needs transcription; images need OCR or vision.','Indique el tipo: audio requiere transcripción; imágenes, OCR o visión.'],'needs-input');
 if(a.format==='media'&&['audio','both'].includes(a.mediaType))add('audio-transcription','solution',['mediaType','writingTask'],['ابتدا صوت را با ابزار تشخیص گفتار به متن تبدیل کنید؛ سپس متن پیاده‌شده وارد ترجمه یا کار انتخابی شما می‌شود. مدل‌های متنی زیر فایل صوت را مستقیم نمی‌خوانند. دقت نام‌ها و عددها را در مرحلهٔ پیاده‌سازی جدا بسنجید.','Transcribe audio first, then run the selected text operation. The text candidates below do not consume audio directly; test names and numbers in transcription separately.','Transcriba el audio antes de la operación textual. Los candidatos no reciben audio directamente; compruebe nombres y cifras en la transcripción.'],'conditional');
 if(a.format==='media'&&a.mediaType==='both')add('image-ocr','solution',['mediaType'],['نوشته‌های تصویر را هم با OCR استخراج کنید و کنار متن صوت قرار دهید؛ ترتیب و منشأ هر بخش حفظ شود.','Extract image text with OCR alongside the transcript, preserving order and provenance.','Extraiga texto de imágenes con OCR junto a la transcripción, conservando orden y origen.'],'conditional');
 if(isLocal(a)&&a.hardware==='gpu'&&positive(a.gpuCount))add('gpu-topology','capacity',['gpuCount','vram','concurrency'],[Number(a.gpuCount)>1?`با ${n.format(Number(a.gpuCount))} کارت، ابتدا یک نمونهٔ مستقل روی هر کارت را برای تقسیم درخواست‌ها آزمایش کنید. اگر یک مدل روی یک کارت جا نمی‌شود، اتصال کارت‌ها و پشتیبانی تقسیم مدل را جدا بررسی کنید؛ ظرفیت حافظه‌ها خودکار جمع نشده است.`:'یک کارت اعلام کرده‌اید؛ صف و تعداد درخواست فعال باید با ظرفیت همین کارت تنظیم شوند.',Number(a.gpuCount)>1?`With ${a.gpuCount} GPUs, test independent replicas first. Sharding a single model requires separate interconnect/runtime verification; memory is not pooled automatically.`:'One GPU was declared; queueing and active requests must fit that device.',Number(a.gpuCount)>1?`Con ${a.gpuCount} GPU, pruebe réplicas independientes. Partir un modelo requiere verificar conexiones y motor; no se suman memorias automáticamente.`:'Se declaró una GPU; cola y solicitudes activas deben ajustarse a ella.'],'conditional');
 if(a.task==='coding'&&a.codeLanguages&&a.codeLanguages!=='unknown')add('project-language','acceptance',['codeLanguages','codeScope'],[`آزمون‌ها را در محیط ${a.codeLanguages} پروژهٔ خودتان اجرا کنید. نسخهٔ کتابخانه‌ها و ابزار ساخت را ثبت کنید تا مقایسهٔ مدل‌ها در شرایط یکسان باشد.`,`Run project tests in the ${a.codeLanguages} environment; pin dependencies and build-tool versions with the test suite.`,`Ejecute pruebas en el entorno ${a.codeLanguages}; fije dependencias y versiones de construcción con las pruebas.`]);

 const tariff=locale==='fa'?undefined:apiTariffs.find(t=>t.id===a.apiCostExample),maxInput=positive(a.maxTokens);
 const tier=tariff?.tiers.find(t=>maxInput&&maxInput<=t.maxInputTokens);
 const apiCost=tariff&&tier&&monthlyTokens&&a.policy==='public'?{usd:(monthlyTokens.input*tier.inputPerMillion+monthlyTokens.output*tier.outputPerMillion)/1e6,tariff,tier,basis:'estimate' as const}:undefined;
 if(apiCost)add('api-example-cost','cost',['apiCostExample','requests','workdays','averageInputTokens','averageOutputTokens','maxTokens','serviceAccess'],[`${tariff!.model} در ${tariff!.region}: برآورد مصرف ماهانه ${n.format(apiCost.usd)} دلار، با تعرفهٔ بررسی‌شده در ${tariff!.reviewedOn}. ورودی هر میلیون ${tier!.inputPerMillion} و خروجی ${tier!.outputPerMillion} دلار؛ سقف این پله ${n.format(tier!.maxInputTokens)} توکن ورودی است.`,`${tariff!.model} in ${tariff!.region}: estimated monthly usage ${n.format(apiCost.usd)} USD at tariffs reviewed ${tariff!.reviewedOn}. Input ${tier!.inputPerMillion} and output ${tier!.outputPerMillion} USD/million; this tier allows up to ${n.format(tier!.maxInputTokens)} input tokens.`,`${tariff!.model} en ${tariff!.region}: consumo mensual estimado de ${n.format(apiCost.usd)} USD, tarifa revisada ${tariff!.reviewedOn}. Entrada ${tier!.inputPerMillion} y salida ${tier!.outputPerMillion} USD/millón; hasta ${n.format(tier!.maxInputTokens)} tokens de entrada.`],'conditional',[],[L('فرض: بدون cache و ابزار پولی؛ میانگین خروجی شامل توکن تفکر قابل‌صورتحساب است. این محاسبه تأیید دسترسی حساب نیست.','Assumes no cache or paid tools; average output includes billable reasoning. This calculation does not confirm account access.','Sin caché ni herramientas de pago; salida media incluye razonamiento facturable. El cálculo no confirma acceso de la cuenta.')],[tariff!.sourceUrl]);
 else if(tariff)add('api-cost-input','cost',['apiCostExample','maxTokens','averageInputTokens','averageOutputTokens','requests'],['برای این تعرفه، بیشترین ورودی و میانگین واقعی توکن‌های ورودی/خروجی لازم است؛ از روی طول معمول، پلهٔ تعرفه را حدس نمی‌زنیم.','This tariff needs maximum input and mean input/output usage; typical length does not determine the billing tier.','La tarifa necesita entrada máxima y consumos medios; la longitud habitual no determina el tramo.'],'needs-input');
 if(apiCost&&a.monthly&&a.monthly!=='unknown'){
  const budgetUsd=a.currency==='usd'?Number(a.monthly):a.currency==='million-toman'&&positive(a.usdRate)?Number(a.monthly)*1e6/Number(a.usdRate):undefined;
  if(budgetUsd!==undefined)add(apiCost.usd>budgetUsd?'api-over-budget':'api-within-budget','cost',['monthly','currency','usdRate','apiCostExample'],[apiCost.usd>budgetUsd?'مصرف نمونهٔ API از سقف ماهانه بالاتر است؛ حجم کار یا تعرفهٔ قابل دسترس باید تغییر کند.':'هزینهٔ توکنی این نمونه در سقف ماهانه جا می‌گیرد؛ راه‌اندازی و پشتیبانی جدا قیمت‌گذاری می‌شوند.',apiCost.usd>budgetUsd?'The API example exceeds the monthly limit; change workload volume or the accessible tariff.':'Example token usage fits the monthly limit; setup and support remain separate.',apiCost.usd>budgetUsd?'El ejemplo API supera el límite mensual; cambie volumen o tarifa accesible.':'Los tokens del ejemplo caben en el límite mensual; instalación y soporte van aparte.'],'conditional');
 }

 const followups=decisions.filter(d=>d.status==='needs-input'&&['load-definition','inspect-equipment','service-pilot'].includes(d.id)).slice(0,2);
 if(followups.length<2&&(!wizardLanguages(a,'source').length||!wizardLanguages(a,'output').length))followups.push({id:'languages',area:'model',conclusion:L('متن‌ها و پاسخ‌های موردنظرتان به چه زبان‌هایی هستند؟ با مشخص‌کردن آن‌ها می‌توانیم مدل‌های مناسب‌تری پیشنهاد کنیم.','Which languages occur in the work? Interface language was not treated as workload language.','¿Qué idiomas aparecen en el trabajo? No se usó el idioma de la interfaz como idioma de trabajo.'),because:[],answerIds:['sourceLanguages','outputLanguages','sourceLanguage','outputLanguage'],evidenceIds:[],status:'needs-input',assumptions:[]});
 const provenance=Object.fromEntries(Object.entries(a).map(([id,value])=>[id,{value,status:value==='unknown'?'unknown':statuses[id]??(wizardQuestions.find(q=>q.id===id)?.kind==='number'?'estimate':'declared')}]));
 return {decisions,retrieval,batch,monthlyTokens,apiCost,costComparison,followups,provenance};
}
