import type { LlmGuideRepository } from './schema';
import type { LlmLocale } from './i18n/runtime';
import { cleanWizard,isLocal,hasTranslationPair,localized,wizardArticles,WIZARD_VERSION,positive,visibleQuestion,wizardQuestions,type WizardAnswers,type MemoryEstimator,type AnswerStatus } from './wizard-core';
import { assessWizardCatalog,selectWizardCandidates,professionalServing,requestedSpecialty } from './wizard-candidates';
import { decideWizard,type WizardDecision } from './wizard-decisions';
import { wizardApiCandidates } from './wizard-api';
export * from './wizard-core';
export { assessWizardCatalog,workloadLanguages } from './wizard-candidates';
export { decideWizard } from './wizard-decisions';
export const QUICK_QUESTIONS=['task','writingTask','codingMode','sourceLanguage','sourceLanguages','outputLanguage','outputLanguages','sources','archiveRole','format','mediaType','inputSize','mode','policy','deployment','hardware','cpuAvx512Fp16','serviceAccess','apiService','apiRegion'];
export function wizardCandidates(repository:LlmGuideRepository,raw:WizardAnswers,locale:LlmLocale,estimate?:MemoryEstimator){return raw.task&&raw.task!=='unknown'&&raw.deployment!=='api'?selectWizardCandidates(assessWizardCatalog(repository,raw,locale,estimate),locale):[];}
export function buildWizardResult(repository:LlmGuideRepository,raw:WizardAnswers,locale:LlmLocale,estimate?:MemoryEstimator,statuses:Record<string,AnswerStatus>={}){
 const a=cleanWizard(raw,locale),L=(fa:string,en:string,es:string)=>localized([fa,en,es],locale);
 const plan=decideWizard(a,locale,statuses),reviews=assessWizardCatalog(repository,a,locale,estimate);
 const discovery=!a.task||a.task==='unknown',candidates=discovery||a.deployment==='api'?[]:selectWizardCandidates(reviews,locale);
 const apiCandidates=discovery?[]:wizardApiCandidates(a,locale);
 const specialists=discovery||!plan.retrieval||a.deployment==='api'?[]:(['embedding',...(a.failure==='ranking'?['reranker']:[])] as ('embedding'|'reranker')[]).flatMap(kind=>selectWizardCandidates(assessWizardCatalog(repository,a,locale,undefined,kind),locale).slice(0,1));
 const decisions:WizardDecision[]=[...plan.decisions,...candidates.map(c=>({id:c.model.id,area:'model' as const,conclusion:c.reason,because:[c.difference??'',c.runtimeReason??'',...c.reasons].filter(Boolean),answerIds:c.answerIds,evidenceIds:c.evidenceIds,status:c.status==='conditional'?'conditional' as const:'supported' as const,assumptions:[]}))];
 if(a.task==='coding'&&['agent','security'].includes(a.codingMode)&&candidates.some(c=>c.model.id==='model:zai-org-glm-5-3-bf16'))decisions.push({
  id:'glm53-cyber-security',area:'deployment',status:'conditional',answerIds:['task','codingMode'],because:[],assumptions:[],
  evidenceIds:["https://www.anthropic.com/research/glm-5-3-and-the-spread-of-advanced-cyber-capabilities", "https://www.nist.gov/news-events/news/2026/09/caisis-assessment-zais-glm-53-cyber-capabilities"],
  conclusion:L("ارزیابی‌های NIST و Anthropic از توان پیشرفتهٔ GLM-5.3 در کشف آسیب‌پذیری و ساخت exploit خبر می‌دهند. نمی‌توان به امتناع مدل به‌عنوان کنترل امنیتی تکیه کرد؛ در آزمون Anthropic، درخواست پوششی، prefill و تغییر وزن این کنترل را دور زده‌اند. مدل و عامل‌های کدنویسی متصل به آن را در sandbox بدون credential و بدون دسترسی آزاد به شبکه اجرا کنید، ابزارها را محدود نگه دارید و همهٔ عملیات را ثبت کنید.","NIST and Anthropic evaluations report advanced vulnerability discovery and exploit development by GLM-5.3. Do not rely on model refusal as a security control: cover stories, prefill and weight modification bypassed it in Anthropic tests. Run the model and its coding agents in a sandbox without credentials or unrestricted network access, limit tools and log all operations.","Las evaluaciones de NIST y Anthropic señalan capacidades avanzadas de GLM-5.3 para descubrir vulnerabilidades y desarrollar exploits. No confíe en el rechazo del modelo como control de seguridad: pretextos, prefill y cambios de pesos lo eludieron en las pruebas de Anthropic. Ejecute el modelo y sus agentes de código en un sandbox sin credenciales ni acceso libre a la red, limite las herramientas y registre todas las operaciones.")
 });
 if(isLocal(a)&&a.hardware==='cpu'&&a.cpuAvx512Fp16==='yes'&&candidates.some(c=>c.runtime==='llama.cpp'))decisions.push({
  id:'llama-avx512-fp16-correctness',area:'deployment',status:'conditional',answerIds:['hardware','cpuAvx512Fp16','deployment'],because:[],assumptions:[],
  evidenceIds:['https://github.com/ggml-org/llama.cpp/releases/tag/b11262','https://github.com/ggml-org/llama.cpp/pull/29545'],
  conclusion:L("پیش‌انتشار b11262؛ اصلاح صحت محاسبه در CPU. در مسیر AVX512-FP16، انباشت FP16 در dot productهای F16 ممکن بود overflow کند و logits متفاوتی بدهد؛ b11262 انباشت را به FP32 منتقل می‌کند. برای این مسیر، خروجی buildهای قدیمی‌تر را پیش از اتکا روی b11262+ حاوی اصلاح #29545 بازآزمایی کنید. این اصلاح شاهد افزایش سرعت نیست و پیش‌انتشار، انتخاب پیش‌فرض تولیدی نمی‌شود.","Prerelease b11262 fixes CPU computation correctness. In the AVX512-FP16 path, FP16 accumulation in F16 dot products could overflow and change logits; b11262 accumulates in FP32. Retest older-build output on b11262+ containing fix #29545 before relying on this path. This is not evidence of a speed increase, and the prerelease is not a production default.","La versión preliminar b11262 corrige el cálculo en CPU. En la ruta AVX512-FP16, la acumulación FP16 de productos escalares F16 podía desbordarse y alterar los logits; b11262 acumula en FP32. Antes de confiar en esta ruta, repita las pruebas de versiones anteriores con b11262+ y la corrección #29545. No demuestra mayor velocidad ni se recomienda por defecto para producción.")
 });
 // A documented experimental alternative; no reviewed GGUF package is selected or sized.
 if(!discovery&&plan.retrieval&&isLocal(a)&&a.format==='media'&&['image','video'].includes(a.mediaType)&&repository.modelProfiles.some(p=>p.modelVersionId.startsWith('model:qwen-qwen3-vl-embedding-')&&p.runGuides.some(g=>g.engine==='llama.cpp')))decisions.push({
  id:'multimodal-embedding-llama',area:'retrieval',status:'conditional',answerIds:['sources','archiveRole','format','mediaType','deployment'],because:[],assumptions:[],
  evidenceIds:['https://github.com/ggml-org/llama.cpp/releases/tag/b11240'],
  conclusion:L('برای RAG چندوجهی و embedding تصویر و ویدئو، Qwen3-VL-Embedding-2B/8B با llama.cpp b11240+ / llama-server یک گزینهٔ آزمایشی است. فایل‌های GGUF سازگار مدل و projector را جداگانه آماده و اعتبارسنجی کنید؛ GGUF رسمی ثبت نشده است. در /v1/embeddings هر شیء {"content": [...]} یک embedding می‌سازد؛ bare content array رد می‌شود و legacy API حفظ شده است. KV prefix reuse برای embedding/rerank غیرفعال است؛ ظرفیت و سرعت را دوباره بسنجید. fa: شاهد ثبت نشده؛ این گزینه تأیید پشتیبانی چندوجهی reranker نیست.',
   'For multimodal RAG and image/video embeddings, Qwen3-VL-Embedding-2B/8B with llama.cpp b11240+ / llama-server is an experimental option. Prepare and validate compatible model and projector GGUF files separately; no official GGUF is recorded. In /v1/embeddings each {"content": [...]} object produces one embedding; bare content arrays are rejected and legacy API formats remain supported. KV prefix reuse is disabled for embedding/rerank; remeasure capacity and speed. Persian evidence is not recorded; this does not establish multimodal reranker support.',
   'Para RAG multimodal y embeddings de imagen/vídeo, Qwen3-VL-Embedding-2B/8B con llama.cpp b11240+ / llama-server es una opción experimental. Prepare y valide por separado los GGUF compatibles del modelo y projector; no se registra GGUF oficial. En /v1/embeddings cada objeto {"content": [...]} produce un embedding; se rechazan arrays content sin envoltura y se mantienen los formatos anteriores. KV prefix reuse está desactivado para embedding/rerank; vuelva a medir capacidad y velocidad. No hay pruebas registradas para persa; no acredita soporte de rerankers multimodales.')
 });
 if(professionalServing(a)&&candidates.some(c=>c.runtime==='vLLM'))decisions.push({
  id:'serving-runtime',area:'deployment',status:'conditional',
  conclusion:L('برای سرویس‌دهی روی GPU، پیشنهاد اول vLLM است. این نرم‌افزار درخواست‌ها را به‌صورت گروهی و پیوسته پردازش می‌کند و برای پاسخ‌گویی به چند کاربر مناسب است. فایل مدل و راهنمای اجرای هر گزینه در بخش تیم فنی آمده است.','For GPU serving, prefer vLLM: continuous batching suits shared workloads. The technical section links each candidate’s selected weight package and runtime guide.','Para servir en GPU, priorice vLLM: los lotes continuos se adaptan al uso compartido. La sección técnica enlaza los pesos y la guía de ejecución elegidos para cada modelo.'),
  because:[],assumptions:[],answerIds:['phase','audience','users','concurrency','hardware','deployment','owner'],evidenceIds:['https://docs.vllm.ai/en/stable/']
 });
 const target=requestedSpecialty(a);
 if(candidates.some(c=>c.runtime==='vLLM'))decisions.push({
  id:'vllm-security-review',area:'deployment',status:'conditional',answerIds:['hardware','deployment'],because:[],assumptions:[],
  evidenceIds:['https://github.com/vllm-project/vllm/security/advisories/GHSA-x6mc-67gf-chw4','https://github.com/vllm-project/vllm/releases/tag/v0.30.0'],
  conclusion:L('اگر vLLM نصب‌شده قدیمی‌تر از 0.30.0 است، هشدارهای امنیتی جدول نرم‌افزار را بررسی کنید؛ 0.30.0 چهار مورد ثبت‌شده را رفع می‌کند. مورد Qwen به frontend پایتون، مسیر ویدئو و ورودی media_io_kwargs وابسته است؛ Rust نیز هشدار مستقل metrics دارد. این ویزارد نسخه، frontend و گزینه‌های ورودی سرویس را نمی‌پرسد و آسیب‌پذیری نصب شما را تشخیص نمی‌دهد. پیش از ارتقا، GPTQ g_idx، --enable-scale-out و سازگاری بستهٔ CUDA/درایور را بررسی کنید.','If installed vLLM predates 0.30.0, review the software table security notices; 0.30.0 fixes the four listed issues. The Qwen issue depends on the Python frontend, video sampling and media_io_kwargs input; Rust has a separate metrics advisory. This wizard does not collect installed version, frontend or service input settings and cannot diagnose your deployment. Before upgrading, review GPTQ g_idx, --enable-scale-out and CUDA package/driver compatibility.','Si vLLM instalado es anterior a 0.30.0, revise los avisos de la tabla; 0.30.0 corrige los cuatro casos. El caso Qwen depende del frontend Python, vídeo y media_io_kwargs; Rust tiene otro aviso de métricas. El asistente no pregunta versión, frontend ni entradas del servicio y no diagnostica su instalación. Antes de actualizar, revise GPTQ g_idx, --enable-scale-out y compatibilidad CUDA/controlador.')
 });
 if(candidates.some(c=>c.runtime==='llama.cpp'))decisions.push({
  id:'llama-rpc-version-review',area:'deployment',status:'conditional',answerIds:['hardware','deployment'],because:[],assumptions:[],
  evidenceIds:['https://github.com/ggml-org/llama.cpp/releases/tag/v0.5.0'],
  conclusion:L('فقط اگر llama.cpp را با RPC بین دستگاه‌ها اجرا می‌کنید: v0.5.0 از پروتکل major 7 استفاده می‌کند و با major 6 در v0.4.1 هماهنگ نیست. major دو سمت باید برابر و minor سرور حداکثر برابر کلاینت باشد؛ build کلاینت و همهٔ سرورها را هماهنگ کنید.','Only if using llama.cpp RPC between machines: v0.5.0 uses protocol major 7, incompatible with v0.4.1 major 6. Both ends need equal major versions and server minor must not exceed client minor; align client and all server builds.','Solo si usa RPC de llama.cpp entre equipos: v0.5.0 usa major 7, incompatible con major 6 de v0.4.1. Ambos extremos necesitan el mismo major y minor del servidor no superior al cliente; alinee todas las compilaciones.')
 });
 if(target&&a.deployment!=='api'&&!candidates.some(c=>c.specialty)){
  const translationNeedsPair=target==='translation'&&!hasTranslationPair(a);
  decisions.push({id:'specialist-fallback',area:'solution',status:translationNeedsPair?'needs-input':'conditional',answerIds:['writingTask','codingMode','sourceLanguage','outputLanguage','hardware','vram','ram','maxTokens'],evidenceIds:[],because:[],assumptions:[],
   conclusion:translationNeedsPair?L('زبان مبدأ و مقصد ترجمه را مشخص کنید. اگر هر دو یک زبان‌اند و منظورتان بازنویسی است، گزینهٔ بازنویسی را انتخاب کنید.','Specify distinct translation source and target languages. If you mean rewriting in the same language, select rewriting.','Indique los idiomas de origen y destino. Si quiere reformular en el mismo idioma, elija reescritura.')
    :L('با محدودیت‌هایی که وارد کرده‌اید، از میان مدل‌های تخصصی بررسی‌شده گزینهٔ مناسبی پیدا نشد. مدل‌های عمومی زیر را برای مقایسه آورده‌ایم؛ محدودیت حافظه، طول متن و شرایط استفاده را در مشخصاتشان ببینید.','No reviewed specialist meets the supplied constraints. The general-purpose models below are comparison candidates; check memory, context and use conditions.','Ningún especialista revisado cumple las restricciones. Los modelos generales son candidatos de comparación; revise memoria, contexto y condiciones de uso.')
  });
 }
 if(['api','compare'].includes(a.deployment)&&a.policy==='public')decisions.push({id:'api-selection',area:'deployment',status:apiCandidates.some(c=>c.accessConfirmed)?'conditional':'needs-input',answerIds:['apiService','apiRegion','serviceAccess'],evidenceIds:apiCandidates.map(c=>c.sourceUrl),because:[],assumptions:[],conclusion:apiCandidates.length?L('گزینه‌های API در بخش جدا با نام ارائه‌دهنده و نسخهٔ خدمت آمده‌اند. نتیجهٔ یک فراخوانی آزمایشی و سقف حساب را پیش از اجرا ثبت کنید.','API candidates list the provider and service revision. Record a trial response and account quotas before deployment.','Los candidatos API indican proveedor y versión. Registre una llamada de prueba y cuotas antes de desplegar.'):L('برای ارائه‌دهنده، منطقه یا محدودیت فعلی، خدمت منطبق در فهرست بررسی‌شده نداریم. نام مدل در فهرست وزن‌های باز، به معنی عرضهٔ API آن نیست.','No reviewed service matches this provider, region or constraints. An open-weight catalog entry is not an API offer.','No hay un servicio revisado para proveedor, región o restricciones. Un modelo abierto no equivale a una oferta API.')});
 const followupPriority:Record<string,number>={'languages':0,'media-type':0,'archive-role':0,'api-selection':1,'service-pilot':1,'inspect-equipment':1,'load-definition':2};
 const followups=[...plan.followups,...decisions.filter(d=>d.status==='needs-input')].filter((d,index,list)=>list.findIndex(x=>x.id===d.id)===index&&d.answerIds.some(id=>wizardQuestions.some(q=>q.id===id&&visibleQuestion(q,a,locale)&&(!a[id]||a[id]==='unknown')))).sort((a,b)=>(followupPriority[a.id]??10)-(followupPriority[b.id]??10)).slice(0,2);
 const byArea=(area:WizardDecision['area'])=>decisions.filter(d=>d.area===area).map(d=>[d.conclusion,...d.assumptions].join(' '));
 // Hypothetical comparisons are separate from the user's input and never certify fit.
 const memoryScenarios=estimate&&isLocal(a)&&(!a.inputTokens||a.inputTokens==='unknown')&&(!a.maxTokens||a.maxTokens==='unknown')&&['cpu','gpu'].includes(a.hardware)&&(!positive(a.concurrency)||Number(a.concurrency)<=128)?candidates.filter(c=>['llama.cpp','Ollama'].includes(c.runtime??'')).flatMap(c=>[4096,16384].flatMap(context=>{
  const assumed={...a,inputTokens:String(context),maxTokens:String(context),outputTokens:'512',concurrency:['active','machines'].includes(a.loadDefinition)&&a.concurrency&&a.concurrency!=='unknown'?a.concurrency:'1',loadDefinition:'active',mode:'interactive'};
  const memory=estimate(c.model,assumed);return memory?[{modelId:c.model.id,memory,basis:'estimate' as const,assumptions:L(`برای مقایسه، ورودی ${new Intl.NumberFormat('fa-IR').format(context)} و پاسخ ۵۱۲ توکنی را با ${new Intl.NumberFormat('fa-IR').format(Number(assumed.concurrency))} درخواست هم‌زمان فرض کرده‌ایم.`,`Comparison assumption: ${context} input, 512 output tokens, ${assumed.concurrency} active requests; not user answers.`,`Supuesto: ${context} tokens de entrada, 512 de salida, ${assumed.concurrency} solicitudes activas; no son respuestas del usuario.`)}]:[];
 })):[];
 const catalogReviews=reviews.map(c=>({...c,selected:candidates.some(s=>s.model.id===c.model.id),selectionReason:c.status==='excluded'?c.reasons.join(' '):candidates.some(s=>s.model.id===c.model.id)?candidates.find(s=>s.model.id===c.model.id)!.difference??c.reason:L('سه گزینهٔ بالا با توجه به کاربرد، زبان، حافظه و نرم‌افزار اجرا برای شروع انتخاب شده‌اند. این مدل هم قابل بررسی است؛ انتخاب‌نشدن آن به معنی کیفیت پایین‌تر نیست.','Not shortlisted after comparing task/language evidence coverage, package size and runtime diversity; this is not a quality verdict.','Fuera de la lista tras comparar pruebas de tarea/idioma, tamaño y diversidad de ejecución; no es un juicio de calidad.')}));
 return {...plan,followups,apiCandidates,decisions,reviews:catalogReviews,memoryScenarios,version:WIZARD_VERSION,catalogReviewed:'2026-09-20 — Qwen3.6 / Qwen3.7',answers:a,candidates,specialists,unknowns:followups.map(d=>d.conclusion),local:isLocal(a),deployment:byArea('deployment').join(' '),production:byArea('operations').join(' '),costPlan:byArea('cost').join(' '),testPlan:byArea('acceptance'),rationale:byArea('solution').join(' '),articles:wizardArticles(a),discovery};
}
