"""Import reviewed Qwen releases from pinned official snapshots. Idempotent; no guessed benchmarks."""
from pathlib import Path
import json,hashlib,re
root=Path(__file__).resolve().parents[1];data=root/'data/llm';src=data/'sources/wizard-2026-09-20'
def read(p):return json.loads(p.read_text())
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
r=read(data/'v0.3.0/repository.json');bindings=read(data/'locales/record-bindings.json');texts={l:read(data/f'locales/records.{l}.json') for l in ['fa','en','es']}
def upsert(k,x):
 r[k]=[v for v in r[k] if v['id']!=x['id']]+[x];return x
def trans(k,x,path,fa,en,es):
 v=x;parts=path.split('/')
 for p in parts[:-1]:v=v[int(p)] if isinstance(v,list) else v[p]
 if isinstance(v,list):v[int(parts[-1])]=fa
 else:v[parts[-1]]=fa
 entity='repository.'+k+'/'+x['id'];key='wizard0920.'+hashlib.sha256((entity+'/'+path).encode()).hexdigest()[:18]
 bindings.setdefault(entity,{})[path]=key
 for l,t in zip(['fa','en','es'],[fa,en,es]):texts[l][key]=t
for short,name,langparams,active in [('27b','Qwen3.6-27B',27,None),('35b','Qwen3.6-35B-A3B',35,3)]:
 meta=read(src/f'qwen36-{short}-api.json');config=read(src/f'qwen36-{short}-config.json');repo='Qwen/'+name;sha=meta['sha'];slug=re.sub('[^a-z0-9]+','-',repo.lower());mid='model:'+slug;eid='evidence:wizard0920-'+slug;url='https://huggingface.co/'+repo;card=url+'/blob/'+sha+'/README.md'
 def known(v,unit=None):return dict(state='known',value=v,evidenceIds=[eid],**({'unit':unit} if unit else {}))
 e=upsert('evidence',dict(id=eid,url=card,title=name+' — official card, config and file inventory',organization='Qwen',accessedOn='2026-09-20',versionRevisionOrCommit=sha,locator='Model overview; Quickstart; config.json; HF API safetensors and siblings',kind='publisher-report',sourceKind='primary',scope=repo,limitations=[],presentationNotes=[]))
 stored=meta['safetensors']['total']/1e9
 m=upsert('models',dict(id=mid,familyId='family:qwen',exactName=name,publisher='Qwen / Alibaba Cloud',version=sha,aliases=[repo],stage='instruct',architecture='moe' if active else 'dense',attentionArchitecture='hybrid',thinkingMode='switchable',totalParametersB=known(stored,'billion-parameters'),activeParametersB=known(active,'billion-parameters') if active else {'state':'not-applicable'},parameterCounts=[dict(scope='language-component',label='',value=known(langparams,'billion-parameters'),approximate=True),dict(scope='stored',label='',value=known(stored,'billion-parameters'),approximate=False)],kind='vision-language',inputModalities=['text','image','video'],outputModalities=['text'],applications=['text-work','document-vision','enterprise-rag','structured-extraction','reasoning-analysis','coding-assistant','agents-tools'],languages=[dict(language='multilingual',declared=known(True))],persianEvidenceStatus='not-evaluated',declaredContext=known(262144,'token'),configurationContext=known(config['text_config']['max_position_embeddings'],'token'),evaluatedContext={'state':'not-measured'},contextExtension=dict(capacity=known(1010000,'token'),condition=''),releaseStatus='available',lastReviewedOn='2026-09-20',license=dict(name=known('Apache-2.0'),url=known(url+'/blob/'+sha+'/LICENSE'),commercialUse=known('allowed'),restrictions=[],evidenceIds=[eid]),evidenceIds=[eid]))
 trans('models',m,'parameterCounts/0/label','جزء زبانی؛ شمار گرد‌شدهٔ ناشر','Language component; publisher rounded count','Componente lingüístico; cifra redondeada del editor')
 trans('models',m,'parameterCounts/1/label','عناصر پارامتری ذخیره‌شده در مخزن','Stored repository parameter elements','Elementos paramétricos almacenados')
 trans('models',m,'contextExtension/condition','نیازمند تنظیم YaRN؛ سقف بومی ۲۶۲٬۱۴۴ توکن است.','Requires YaRN configuration; native context is 262,144 tokens.','Requiere configurar YaRN; contexto nativo de 262.144 tokens.')
 files=[dict(path=f['rfilename'],url=url+'/resolve/'+sha+'/'+f['rfilename'],bytes=f['size']) for f in meta['siblings'] if f['rfilename'].endswith('.safetensors')];total=sum(f['bytes'] for f in files)
 art=upsert('artifacts',dict(id='artifact:'+slug+'-official',modelVersionId=mid,baseRevision=sha,publisher='Qwen',repositoryUrl=url,repositoryRevision=sha,format='safetensors',quantization={'state':'not-applicable'},weightPrecision='bf16',activationPrecision={'state':'unknown'},size=known(total/2**30,'GiB'),authority='official',evidenceIds=[eid]))
 listing=upsert('artifactListings',dict(id='artifact-listing:'+slug+'-official',modelVersionId=mid,baseModelRepository=repo,baseRevision=sha,publisher='Qwen',authority='official',format='safetensors',variant='BF16',precision='bf16',repositoryUrl=url,filesUrl=url+'/tree/'+sha,repositoryRevision=sha,files=files,totalBytes=total,verifiedOn='2026-09-20',evidenceIds=[eid]))
 p=upsert('modelProfiles',dict(id='model-profile:'+slug,modelVersionId=mid,introduction='',roleSummary='',distinguishingFeatures=[''],languageSummary='',officialUrl=card,runGuides=[dict(label='vLLM',engine='vLLM',href=card,conditions=[''],evidenceIds=[eid]),dict(label='SGLang',engine='SGLang',href=card,conditions=[''],evidenceIds=[eid])],evidenceIds=[eid]))
 trans('modelProfiles',p,'introduction',f'{name} متن، تصویر و ویدئو را می‌خواند. وزن رسمی BF16 ثبت شده؛ حافظهٔ اجرای توجه ترکیبی باید با موتور واقعی سنجیده شود.',f'{name} accepts text, images and video. Official BF16 weights are recorded; hybrid-attention runtime memory needs engine-specific measurement.',f'{name} acepta texto, imágenes y vídeo. Pesos BF16 oficiales registrados; la memoria de atención híbrida requiere medición específica del motor.')
 trans('modelProfiles',p,'roleSummary','مدل متن و تصویر با توجه ترکیبی','Text and vision model with hybrid attention','Modelo textual y visual con atención híbrida')
 trans('modelProfiles',p,'distinguishingFeatures/0',f'جزء زبانی {langparams} میلیارد'+(' با ۳ میلیارد فعال؛ حافظه بر اساس همهٔ وزن‌هاست.' if active else '؛ ظرفیت بومی ۲۶۲٬۱۴۴ توکن.'),f'{langparams}B language component'+('; 3B active, but memory covers all weights.' if active else '; native 262,144-token context.'),f'Componente lingüístico de {langparams}B'+('; 3B activos, pero la memoria incluye todos los pesos.' if active else '; contexto nativo de 262.144 tokens.'))
 trans('modelProfiles',p,'languageSummary','چندزبانه؛ آزمون فارسی هم‌سنخ در این ورود داده افزوده نشده است.','Multilingual; no matched Persian evaluation was added in this import.','Multilingüe; esta importación no añade evaluación comparable en persa.')
 for i,minimum in enumerate(['vLLM ≥ 0.19.0','SGLang ≥ 0.5.10']):trans('modelProfiles',p,f'runGuides/{i}/conditions/0',minimum+'؛ برای حالت غیرتفکری، enable_thinking=false در تنظیم درخواست.',minimum+'; non-thinking mode uses enable_thinking=false in request configuration.',minimum+'; el modo sin razonamiento usa enable_thinking=false en la solicitud.')
 for app,role in [('text-work','text-generation'),('document-vision','vision'),('enterprise-rag','grounded-generation'),('structured-extraction','structured-output'),('reasoning-analysis','reasoning'),('coding-assistant','coding'),('agents-tools','tool-use')]:
  u=upsert('modelUseGuidance',dict(id='model-use:'+slug+':'+app,modelVersionId=mid,applicationId=app,role=role,summary='',description='',distinguishingFeature='',conditions=[],basis='editorial-analysis',evidenceIds=[eid]))
  for f,pf in [('summary','roleSummary'),('description','introduction'),('distinguishingFeature','distinguishingFeatures/0')]:
   path=bindings['repository.modelProfiles/'+p['id']][pf];trans('modelUseGuidance',u,f,*[texts[l][path] for l in ['fa','en','es']])
write(data/'v0.3.0/repository.json',r);write(data/'locales/record-bindings.json',bindings)
for l,t in texts.items():write(data/f'locales/records.{l}.json',t)
m=read(data/'v0.3.0/manifest.json');m['asOf']='2026-09-20';m['baseModels']=len(r['models']);m['update20260920']={'models':2,'coverageAudit':'../coverage-audit-2026-09-20.json'};write(data/'v0.3.0/manifest.json',m)
write(data/'coverage-audit-2026-09-20.json',{'reviewedOn':'2026-09-20','scope':'Requested Qwen3.6 open-weight and Qwen3.7 API releases only; not a full-family or whole-catalog completeness claim.','checked':['Qwen3.6-27B','Qwen3.6-35B-A3B','Qwen3.7-Plus','Qwen3.7-Max'],'sources':['https://huggingface.co/Qwen/Qwen3.6-27B','https://huggingface.co/Qwen/Qwen3.6-35B-A3B','https://qwen.ai/apiplatform','https://www.alibabacloud.com/help/en/model-studio/qwen3-7-plus'],'otherFamilies':'Not re-audited in this update.'})
write(data/'api-models.json',[{'id':'qwen3.7-plus','name':'Qwen3.7-Plus','provider':'Alibaba Cloud Model Studio / Qwen API','snapshot':'qwen3.7-plus-2026-05-26','input':['text','image','video'],'output':['text'],'contextTokens':1000000,'availability':'api-available','selfHosting':'not-verified','reviewedOn':'2026-09-20','sourceUrl':'https://www.alibabacloud.com/help/en/model-studio/qwen3-7-plus','platformUrl':'https://qwen.ai/apiplatform'},{'id':'qwen3.7-max','name':'Qwen3.7-Max','provider':'Qwen API','snapshot':'qwen3.7-max-2026-05-20','input':['text'],'output':['text'],'contextTokens':1000000,'availability':'api-available','selfHosting':'not-verified','reviewedOn':'2026-09-20','sourceUrl':'https://qwen.ai/apiplatform','platformUrl':'https://www.alibabacloud.com/help/en/model-studio/web-search'}])
print('Imported 2 pinned open-weight models; 2 separate API records; no fabricated benchmark rows.')
