import { mkdir, readFile, writeFile } from 'node:fs/promises';

// Bundle the small, committed subsets with the application's versioned CSS.
// Older pages may still use static/fonts/icons, so retain those public files.
const source = new URL('../static/fonts/icons/', import.meta.url);
const output = new URL('../src/lib/generated/icons.css', import.meta.url);
let css = await readFile(new URL('icons.css', source), 'utf8');
for (const style of ['solid', 'regular', 'brands']) {
  const font = await readFile(new URL(`${style}.woff2`, source));
  const reference = `url(${style}.woff2)`;
  if (!css.includes(reference)) throw new Error(`Missing icon font reference: ${reference}`);
  css = css.replaceAll(reference, `url("data:font/woff2;base64,${font.toString('base64')}")`);
}
await mkdir(new URL('.', output), { recursive: true });
await writeFile(output, '/* Generated by scripts/prepare-icons.mjs; do not edit. */\n' + css);
console.log('Prepared icon CSS with embedded font subsets.');
